In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from matplotlib import rc
import matplotlib.pyplot as plt


rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus']=False

# 전체 데이터

In [13]:
total = pd.read_csv('C:/cakd7/git/2차 프로젝트/second_projects/생성데이터/total_cust_ratio.csv', index_col = 0)
total.head()

,1분기 대비2분기 증감여부,2분기 대비3분기 증감여부,3분기 대비4분기 증감여부,4분기 대비5분기 증감여부,5분기 대비6분기 증감여부,6분기 대비7분기 증감여부,7분기 대비8분기 증감여부
CUSTNO,,,,,,,
1,3,3,3,1,2,3,1
2,2,4,1,4,1,4,2
3,4,3,2,2,3,3,2
4,4,2,1,3,3,3,2
6,3,3,2,3,2,3,2

In [27]:
# 1분기
year2014_q1 = pd.read_csv('생성데이터/weight_plus_2014_q1.csv', index_col = 0)
year2014_q1['purchase_sum'] = year2014_q1.apply(lambda x:x.sum(), axis = 1)

# 2분기
year2014_q2 = pd.read_csv('생성데이터/weight_plus_2014_q2.csv', index_col = 0)
year2014_q2['purchase_sum'] = year2014_q2.apply(lambda x:x.sum(), axis = 1)

# 3분기
year2014_q3 = pd.read_csv('생성데이터/weight_plus_2014_q3.csv', index_col = 0)
year2014_q3['purchase_sum'] = year2014_q3.apply(lambda x:x.sum(), axis = 1)

#4분기
year2014_q4 = pd.read_csv('생성데이터/weight_plus_2014_q4.csv', index_col = 0)
year2014_q4['purchase_sum'] = year2014_q4.apply(lambda x:x.sum(), axis = 1)

#5분기
year2015_q1 = pd.read_csv('생성데이터/weight_plus_2015_q1.csv', index_col = 0)
year2015_q1['purchase_sum'] = year2015_q1.apply(lambda x:x.sum(), axis = 1)

# 6분기
year2015_q2 = pd.read_csv('생성데이터/weight_plus_2015_q2.csv', index_col = 0)
year2015_q2['purchase_sum'] = year2015_q2.apply(lambda x:x.sum(), axis = 1)

#7분기
year2015_q3 = pd.read_csv('생성데이터/weight_plus_2015_q3.csv', index_col = 0)
year2015_q3['purchase_sum'] = year2015_q3.apply(lambda x:x.sum(), axis = 1)

#8분기
year2015_q4 = pd.read_csv('생성데이터/weight_plus_2015_q4.csv', index_col = 0)
year2015_q4['purchase_sum'] = year2015_q4.apply(lambda x:x.sum(), axis = 1)

# # 데이터 리스트
# df_li = [year2014_q1, year2014_q2, year2014_q3, year2014_q4, year2015_q1, year2015_q2, year2015_q3, year2015_q4]
# total_columns = year2015_q3.columns.tolist()

# plus_or_minus_cust = []
# for i in total_columns:
#     feature = i + '_증감여부'
#     plus_or_minus_cust.append(feature)
# plus_or_minus_cust

# def quater_weight_df(x, y): #1분기 대비 2분기 or 1분기 대비 3분기 각 분기 대입
#     # 기준 원본 데이터
#     df_q1 = df_li[x-1]
#     # 비교할 원본 데이터
#     df_q2 = df_li[y-1]

#     # 대입할 데이터프레임 생성
#     total_df = pd.DataFrame(columns = plus_or_minus_cust, index = year2015_q3.index)

#     # 각 컬럼명 
#     for i in total_columns:
#         # 각 컬럼별 평균 증감율 = (비교할 데이터 - 기준 원본 데이터)/기준 원본 데이터
#         mean_ratio = (df_q2.loc[:, i].sum() - df_q1.loc[:, i].sum())/df_q1.loc[:, i].sum()

#         # 기준 금액 : 기준 원본데이터 * (1+mean_ratio)
#         stand_price = df_q1.loc[:, i] * (1+mean_ratio)
#         # 기준금액 컬럼명
#         stand_column = i + '_기준금액'


#         # 기준 금액 비교할 데이터프레임에 추가
#         df_q2[stand_column] = stand_price

#         # 비교할 원본 데이터 금액 과 기준금액 비교 후 크면 2, 작으면 0, 같으면 1 대입 
#         # 비교할 원본 금액과 기준 금액 컬럼만 따로 추출
#         df_whos_ = df_q2[[i, stand_column]]

#         # 증가 고객
#         df_whos_plus = df_whos_[df_whos_[i] > df_whos_[stand_column]] # 기준금액 보다 큰 경우
#         # 감소 고객
#         df_whos_minus = df_whos_[df_whos_[i] < df_whos_[stand_column]] # 기준금액 보다 작은 경우

#         # 유지 고객
#         df_whos_same = df_whos_[df_whos_[i] == df_whos_[stand_column]] # 기준금액이랑 차이 없음

#         # total_df에 값 대입
#         input_column_name = i + '_증감여부'
#         # 증가면 0
#         total_df.loc[df_whos_plus.index, input_column_name] = 0
#         # 감소면 1
#         total_df.loc[df_whos_minus.index, input_column_name] = 1

#     return total_df['purchase_sum_증감여부']

# 1분기

In [6]:
year2014_q1.head()

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
CUSTNO,,,,,,,,,,,,,,,,,,,
1,0.0,405723.634896,0.000000,7.583585e+05,0.000000,69247.331249,0.0,0.0,108156.932364,951553.888033,0.000000,7.571291e+05,2.407699e+06,0.000000,3.197202e+06,2.085722e+05,0.000000,494024.599590,9.357667e+06
2,0.0,583637.809185,165551.643573,2.595070e+06,32409.891463,0.000000,0.0,0.0,118770.365673,480907.463277,0.000000,2.381060e+06,6.663384e+06,0.000000,3.346182e+05,1.260826e+06,0.000000,142828.453994,1.475906e+07
3,0.0,622.912438,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.0,0.000000,20188.685897,186088.649532,1.002090e+05,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,3.071093e+05
4,0.0,199134.724691,209168.983266,0.000000e+00,0.000000,149534.092118,0.0,0.0,0.000000,7408.692072,6620.788829,5.918005e+05,3.341737e+04,19140.047384,8.182982e+04,0.000000e+00,0.000000,50447.136068,1.348502e+06
6,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.0,0.000000,246042.663720,357210.178316,5.195147e+05,4.422149e+05,96338.238501,4.263169e+05,0.000000e+00,51997.178419,36784.370050,2.176419e+06

In [7]:
year2014_q1.corr()

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
가구인테리어/잡화_고가,1.000000,0.047759,0.068647,0.098089,-0.010988,0.057619,0.000300,-0.017401,0.063259,0.013408,-0.039660,0.001449,0.124204,-0.009378,0.070197,0.101957,-0.032225,0.062128,0.426236
가구인테리어/잡화_저가,0.047759,1.000000,0.079130,0.071053,-0.005268,0.059717,-0.003799,-0.005063,0.046916,0.014001,-0.049487,0.006645,0.091342,0.366054,0.074636,0.074109,0.004025,0.064295,0.145346
가구인테리어/잡화_중가,0.068647,0.079130,1.000000,0.052898,-0.009020,0.084058,-0.001675,-0.021257,0.063171,0.018431,-0.043667,-0.001552,0.096834,-0.010791,0.232169,0.058243,-0.023437,0.050833,0.259305
가전/레저취미/멀티샵_고가,0.098089,0.071053,0.052898,1.000000,-0.008897,0.204416,-0.001216,-0.017504,0.060530,0.016438,-0.035750,0.002688,0.117544,-0.013682,0.062590,0.373265,-0.023997,0.123893,0.291428
가전/레저취미/멀티샵_저가,-0.010988,-0.005268,-0.009020,-0.008897,1.000000,-0.008851,0.002010,0.056267,-0.012939,0.001304,0.021765,0.002985,-0.018357,0.017035,-0.013307,-0.014037,0.058572,-0.003093,0.005720
가전/레저취미/멀티샵_중가,0.057619,0.059717,0.084058,0.204416,-0.008851,1.000000,0.001174,-0.013547,0.125336,0.008031,-0.042667,-0.002090,0.072488,-0.010958,0.118241,0.134335,-0.023145,0.059468,0.241095
교육문화/아동_고가,0.000300,-0.003799,-0.001675,-0.001216,0.002010,0.001174,1.000000,0.062194,0.085327,0.001741,-0.000597,0.000569,-0.003859,0.005215,-0.002636,-0.002665,0.016696,-0.003102,0.017823
교육문화/아동_저가,-0.017401,-0.005063,-0.021257,-0.017504,0.056267,-0.013547,0.062194,1.000000,0.050184,0.003712,0.020088,0.009359,-0.037784,0.043162,-0.028598,-0.026492,0.170682,-0.011451,-0.015059
교육문화/아동_중가,0.063259,0.046916,0.063171,0.060530,-0.012939,0.125336,0.085327,0.050184,1.000000,0.024297,-0.054228,0.001532,0.085625,-0.013035,0.084904,0.094979,-0.022778,0.046672,0.165169
식품/생활_고가,0.013408,0.014001,0.018431,0.016438,0.001304,0.008031,0.001741,0.003712,0.024297,1.000000,0.163451,0.389842,0.023458,-0.002957,0.008617,0.029001,-0.002080,0.017167,0.575164
식품/생활_저가,-0.039660,-0.049487,-0.043667,-0.035750,0.021765,-0.042667,-0.000597,0.020088,-0.054228,0.163451,1.000000,0.685922,-0.060835,0.008800,-0.054456,-0.040771,0.111274,-0.036488,0.283352
식품/생활_중가,0.001449,0.006645,-0.001552,0.002688,0.002985,-0.002090,0.000569,0.009359,0.001532,0.389842,0.685922,1.000000,0.010277,0.141082,-0.003484,0.008552,0.023248,0.000893,0.554756
의류/이미용_고가,0.124204,0.091342,0.096834,0.117544,-0.018357,0.072488,-0.003859,-0.037784,0.085625,0.023458,-0.060835,0.010277,1.000000,-0.021901,0.122454,0.129706,-0.052835,0.101226,0.318313
의류/이미용_저가,-0.009378,0.366054,-0.010791,-0.013682,0.017035,-0.010958,0.005215,0.043162,-0.013035,-0.002957,0.008800,0.141082,-0.021901,1.000000,-0.013076,-0.014889,0.066648,-0.002204,0.098869
의류/이미용_중가,0.070197,0.074636,0.232169,0.062590,-0.013307,0.118241,-0.002636,-0.028598,0.084904,0.008617,-0.054456,-0.003484,0.122454,-0.013076,1.000000,0.064496,-0.038357,0.058867,0.532498
침구/주방_고가,0.101957,0.074109,0.058243,0.373265,-0.014037,0.134335,-0.002665,-0.026492,0.094979,0.029001,-0.040771,0.008552,0.129706,-0.014889,0.064496,1.000000,-0.018695,0.182427,0.249295
침구/주방_저가,-0.032225,0.004025,-0.023437,-0.023997,0.058572,-0.023145,0.016696,0.170682,-0.022778,-0.002080,0.111274,0.023248,-0.052835,0.066648,-0.038357,-0.018695,1.000000,0.018420,-0.024824
침구/주방_중가,0.062128,0.064295,0.050833,0.123893,-0.003093,0.059468,-0.003102,-0.011451,0.046672,0.017167,-0.036488,0.000893,0.101226,-0.002204,0.058867,0.182427,0.018420,1.000000,0.141082
purchase_sum,0.426236,0.145346,0.259305,0.291428,0.005720,0.241095,0.017823,-0.015059,0.165169,0.575164,0.283352,0.554756,0.318313,0.098869,0.532498,0.249295,-0.024824,0.141082,1.000000

In [12]:
year2014_q1.corr().sort_values(by=['purchase_sum'], ascending = False)[['purchase_sum']][1:]

                purchase_sum
식품/생활_고가            0.575164
식품/생활_중가            0.554756
의류/이미용_중가           0.532498
가구인테리어/잡화_고가        0.426236
의류/이미용_고가           0.318313
가전/레저취미/멀티샵_고가      0.291428
식품/생활_저가            0.283352
가구인테리어/잡화_중가        0.259305
침구/주방_고가            0.249295
가전/레저취미/멀티샵_중가      0.241095
교육문화/아동_중가          0.165169
가구인테리어/잡화_저가        0.145346
침구/주방_중가            0.141082
의류/이미용_저가           0.098869
교육문화/아동_고가          0.017823
가전/레저취미/멀티샵_저가      0.005720
교육문화/아동_저가         -0.015059
침구/주방_저가           -0.024824

In [15]:
df_li = [year2014_q1, year2014_q2, year2014_q3, year2014_q4, year2015_q1, year2015_q2, year2015_q3, year2015_q4]

for ind, df in enumerate(df_li):
    print(f'########## {ind+1}분기의 총 매출액 상관관계 ###########')
    
    display(df.corr().sort_values(by=['purchase_sum'], ascending = False)[['purchase_sum']][1:])

########## 1분기의 총 매출액 상관관계 ###########

                purchase_sum
식품/생활_고가            0.575164
식품/생활_중가            0.554756
의류/이미용_중가           0.532498
가구인테리어/잡화_고가        0.426236
의류/이미용_고가           0.318313
가전/레저취미/멀티샵_고가      0.291428
식품/생활_저가            0.283352
가구인테리어/잡화_중가        0.259305
침구/주방_고가            0.249295
가전/레저취미/멀티샵_중가      0.241095
교육문화/아동_중가          0.165169
가구인테리어/잡화_저가        0.145346
침구/주방_중가            0.141082
의류/이미용_저가           0.098869
교육문화/아동_고가          0.017823
가전/레저취미/멀티샵_저가      0.005720
교육문화/아동_저가         -0.015059
침구/주방_저가           -0.024824

########## 2분기의 총 매출액 상관관계 ###########

                purchase_sum
식품/생활_고가            0.674621
의류/이미용_중가           0.408424
식품/생활_중가            0.402388
가전/레저취미/멀티샵_중가      0.374003
가구인테리어/잡화_고가        0.369447
의류/이미용_고가           0.366942
가전/레저취미/멀티샵_고가      0.321697
교육문화/아동_중가          0.260183
가구인테리어/잡화_중가        0.219512
침구/주방_고가            0.195036
식품/생활_저가            0.152121
침구/주방_중가            0.122949
가구인테리어/잡화_저가        0.116760
의류/이미용_저가           0.110514
교육문화/아동_고가          0.018947
가전/레저취미/멀티샵_저가      0.011987
교육문화/아동_저가         -0.010017
침구/주방_저가           -0.032998

########## 3분기의 총 매출액 상관관계 ###########

                purchase_sum
의류/이미용_중가           0.533624
식품/생활_고가            0.493592
가구인테리어/잡화_고가        0.482766
의류/이미용_고가           0.433753
가구인테리어/잡화_중가        0.372740
가전/레저취미/멀티샵_고가      0.336548
식품/생활_중가            0.328839
가전/레저취미/멀티샵_중가      0.290426
침구/주방_고가            0.290135
의류/이미용_저가           0.213686
교육문화/아동_중가          0.198156
침구/주방_중가            0.175328
식품/생활_저가            0.126682
가구인테리어/잡화_저가        0.123375
가전/레저취미/멀티샵_저가      0.019352
교육문화/아동_고가          0.018587
교육문화/아동_저가         -0.014858
침구/주방_저가           -0.038615

########## 4분기의 총 매출액 상관관계 ###########

                purchase_sum
의류/이미용_중가           0.838660
의류/이미용_고가           0.468735
가구인테리어/잡화_중가        0.413692
가구인테리어/잡화_고가        0.348821
가전/레저취미/멀티샵_중가      0.250351
가전/레저취미/멀티샵_고가      0.234694
식품/생활_중가            0.205211
식품/생활_고가            0.195798
침구/주방_고가            0.183690
가구인테리어/잡화_저가        0.156020
교육문화/아동_중가          0.144777
침구/주방_중가            0.112174
식품/생활_저가            0.095985
가전/레저취미/멀티샵_저가      0.027789
의류/이미용_저가           0.019784
교육문화/아동_고가          0.019335
교육문화/아동_저가          0.006467
침구/주방_저가           -0.022041

########## 5분기의 총 매출액 상관관계 ###########

                purchase_sum
의류/이미용_중가           0.666303
가구인테리어/잡화_고가        0.543471
의류/이미용_고가           0.407080
식품/생활_고가            0.392225
가전/레저취미/멀티샵_고가      0.354455
가전/레저취미/멀티샵_중가      0.336387
식품/생활_중가            0.313892
침구/주방_고가            0.308412
가구인테리어/잡화_중가        0.254096
교육문화/아동_중가          0.230532
가구인테리어/잡화_저가        0.204447
침구/주방_중가            0.152916
의류/이미용_저가           0.048020
식품/생활_저가            0.032022
교육문화/아동_고가          0.030667
가전/레저취미/멀티샵_저가      0.016906
교육문화/아동_저가         -0.009415
침구/주방_저가           -0.019150

########## 6분기의 총 매출액 상관관계 ###########

                purchase_sum
의류/이미용_중가           0.756793
가구인테리어/잡화_고가        0.513314
가구인테리어/잡화_중가        0.497635
의류/이미용_고가           0.375978
식품/생활_고가            0.311373
가전/레저취미/멀티샵_고가      0.309998
가전/레저취미/멀티샵_중가      0.290257
침구/주방_고가            0.254259
식품/생활_중가            0.239921
침구/주방_중가            0.184910
교육문화/아동_중가          0.181669
가구인테리어/잡화_저가        0.144515
교육문화/아동_고가          0.028970
가전/레저취미/멀티샵_저가      0.016351
교육문화/아동_저가         -0.005791
침구/주방_저가           -0.011756
의류/이미용_저가          -0.015362
식품/생활_저가           -0.091294

########## 7분기의 총 매출액 상관관계 ###########

                purchase_sum
의류/이미용_중가           0.797989
가구인테리어/잡화_고가        0.464533
의류/이미용_고가           0.303589
가전/레저취미/멀티샵_고가      0.301423
식품/생활_고가            0.293982
가전/레저취미/멀티샵_중가      0.279627
침구/주방_고가            0.272142
가구인테리어/잡화_중가        0.257191
식품/생활_중가            0.209445
침구/주방_중가            0.182874
교육문화/아동_중가          0.151725
가구인테리어/잡화_저가        0.132529
식품/생활_저가            0.062963
의류/이미용_저가           0.059402
교육문화/아동_고가          0.031217
교육문화/아동_저가          0.012337
침구/주방_저가           -0.001520
가전/레저취미/멀티샵_저가     -0.015300

########## 8분기의 총 매출액 상관관계 ###########

                purchase_sum
의류/이미용_중가           0.769497
가전/레저취미/멀티샵_중가      0.451860
가구인테리어/잡화_고가        0.415056
식품/생활_고가            0.404717
교육문화/아동_중가          0.338117
의류/이미용_고가           0.318008
가전/레저취미/멀티샵_고가      0.273885
가구인테리어/잡화_중가        0.233462
식품/생활_중가            0.232997
침구/주방_고가            0.224763
가구인테리어/잡화_저가        0.140476
침구/주방_중가            0.140312
식품/생활_저가            0.083955
교육문화/아동_고가          0.019780
가전/레저취미/멀티샵_저가      0.009398
교육문화/아동_저가         -0.003378
의류/이미용_저가          -0.011595
침구/주방_저가           -0.022375

In [25]:
year2014_q2

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
CUSTNO,,,,,,,,,,,,,,,,,,,
1,0.000000,396977.723964,929676.672404,1.408529e+06,0.000000,0.000000,0.000000,0.000000,72849.882826,2.872480e+06,747.380988,5.212412e+05,1.455276e+06,0.000000,3.707521e+06,0.000000e+00,0.000000,0.000000,1.136530e+07
2,0.000000,529204.667919,285812.420005,1.481466e+06,0.000000,236452.983657,0.000000,0.000000,348299.914552,7.926138e+05,0.000000,1.772862e+06,2.887972e+06,0.000000,8.224038e+05,1.130607e+06,0.000000,115137.689850,1.040283e+07
3,0.000000,1649.400548,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,2.854301e+04,263918.163945,1.781810e+05,0.000000e+00,0.000000,8.366903e+04,0.000000e+00,0.000000,0.000000,5.559606e+05
4,0.000000,150865.170151,303519.237132,1.166910e+05,5053.969564,136807.356782,0.000000,0.000000,0.000000,7.602215e+04,62879.653776,9.103053e+05,7.823605e+05,15053.848604,1.260056e+06,0.000000e+00,5983.754558,0.000000,3.825598e+06
6,39405.980611,112159.237284,268490.733028,0.000000e+00,14384.374914,0.000000,0.000000,0.000000,0.000000,2.386345e+05,228323.895273,6.728968e+05,3.810956e+05,121434.378739,9.726524e+05,9.652073e+04,47072.202527,0.000000,3.193071e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.000000,1649.400548,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,25297.843195,1.273762e+05,29666.042677,7.502804e+05,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,9.342699e+05
19334,0.000000,0.000000,0.000000,0.000000e+00,15453.483860,0.000000,0.000000,33274.023109,32393.097654,1.179315e+05,307231.383459,2.144248e+06,0.000000e+00,43134.294200,0.000000e+00,0.000000e+00,35503.610380,0.000000,2.729169e+06
19335,0.000000,63007.100945,0.000000,0.000000e+00,79697.212359,59922.685415,83358.375687,329805.829047,204102.208340,4.228144e+05,162331.150556,8.438089e+05,0.000000e+00,375754.097056,4.518127e+04,0.000000e+00,156215.885673,46726.013571,2.872725e+06
19336,0.000000,53880.417911,51350.686645,0.000000e+00,0.000000,8601.804842,0.000000,0.000000,0.000000,7.819874e+05,0.000000,5.369106e+05,3.654908e+05,24989.388683,1.647391e+06,0.000000e+00,0.000000,57908.307417,3.528510e+06
19337,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,33044.204742,3.893259e+04,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,7.197679e+04

In [31]:
df_ = year2014_q2+year2014_q1+year2014_q3+year2014_q4+year2015_q2+year2015_q1+year2015_q3+year2015_q4

In [32]:
df_

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
CUSTNO,,,,,,,,,,,,,,,,,,,
1,1.093448e+06,1.801136e+06,3.121841e+06,7.928046e+06,0.000000,7.727253e+05,0.000000,0.000000e+00,1.810068e+05,5.541699e+06,1.982385e+05,6.987674e+06,1.168049e+07,1.420765e+04,3.151413e+07,1.117636e+07,69192.988578,3.169853e+06,8.525005e+07
2,2.099150e+06,4.133839e+06,8.243740e+05,1.531436e+07,151250.500454,2.364530e+05,0.000000,0.000000e+00,1.763678e+06,3.079993e+06,9.422361e+03,1.209775e+07,3.584489e+07,2.172402e+05,1.546426e+07,7.204342e+06,0.000000,5.147151e+06,1.035882e+08
3,0.000000e+00,1.741021e+04,0.000000e+00,0.000000e+00,29619.169986,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,2.113077e+05,1.578197e+06,1.217957e+06,0.000000e+00,7.013903e+03,8.366903e+04,0.000000e+00,6812.722249,0.000000e+00,3.151986e+06
4,0.000000e+00,9.787516e+05,7.183303e+05,4.887139e+05,8624.499645,8.440781e+05,0.000000,7.231205e+04,0.000000e+00,4.661657e+05,3.456699e+05,5.136306e+06,1.847989e+06,3.810821e+05,5.125107e+06,4.732095e+05,26714.234235,2.574531e+05,1.717051e+07
6,3.635425e+05,5.805950e+05,6.037304e+05,3.114943e+04,50776.321983,0.000000e+00,0.000000,3.111367e+03,0.000000e+00,2.672085e+06,1.875039e+06,4.816210e+06,5.698200e+06,9.418732e+05,5.474293e+06,1.307675e+06,233035.436916,1.793226e+05,2.483064e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.000000e+00,4.195970e+03,0.000000e+00,0.000000e+00,23377.626629,0.000000e+00,0.000000,2.810451e+03,4.896434e+04,2.985236e+05,2.366664e+05,4.111766e+06,0.000000e+00,0.000000e+00,4.420455e+04,0.000000e+00,5711.847937,0.000000e+00,4.776220e+06
19334,0.000000e+00,9.854240e+04,0.000000e+00,0.000000e+00,62549.958880,0.000000e+00,631818.443008,2.005338e+05,6.565516e+05,4.470965e+05,1.816112e+06,7.771108e+06,0.000000e+00,3.698686e+05,2.046101e+05,0.000000e+00,168068.459890,0.000000e+00,1.242686e+07
19335,0.000000e+00,8.077722e+05,6.279455e+05,0.000000e+00,431972.887647,2.676439e+05,249937.131654,1.361556e+06,2.080988e+06,1.249268e+06,9.786724e+05,6.284089e+06,9.628908e+04,1.232199e+06,1.013108e+05,0.000000e+00,804557.310824,1.158408e+05,1.669004e+07
19336,1.061195e+06,1.113646e+06,1.095422e+06,0.000000e+00,0.000000,1.479755e+06,0.000000,0.000000e+00,2.573710e+05,1.335860e+06,0.000000e+00,3.488905e+06,4.231829e+06,4.722752e+04,1.613435e+07,3.844398e+05,0.000000,2.971506e+05,3.092715e+07
19337,0.000000e+00,2.136078e+03,1.278379e+05,0.000000e+00,26219.881429,0.000000e+00,0.000000,1.405226e+03,0.000000e+00,1.418532e+05,1.759481e+06,2.449978e+06,0.000000e+00,2.688663e+03,3.158078e+05,0.000000e+00,49498.226029,0.000000e+00,4.876906e+06

In [33]:
df_.corr().sort_values(by=['purchase_sum'], ascending = False)[['purchase_sum']][1:]

                purchase_sum
의류/이미용_중가           0.718949
가구인테리어/잡화_고가        0.471733
가전/레저취미/멀티샵_중가      0.446363
의류/이미용_고가           0.444734
식품/생활_고가            0.417700
가구인테리어/잡화_중가        0.389894
가전/레저취미/멀티샵_고가      0.355239
침구/주방_고가            0.330090
식품/생활_중가            0.321938
교육문화/아동_중가          0.265415
침구/주방_중가            0.251436
가구인테리어/잡화_저가        0.187688
의류/이미용_저가           0.072435
식품/생활_저가            0.067894
교육문화/아동_고가          0.022071
가전/레저취미/멀티샵_저가      0.014831
교육문화/아동_저가         -0.021758
침구/주방_저가           -0.073714

In [24]:
df_li = [year2014_q2, year2014_q3, year2014_q4, year2015_q1, year2015_q2, year2015_q3, year2015_q4]

df_ = year2014_q1
for i in df_li:
    display(df_)
    df_ += i

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
CUSTNO,,,,,,,,,,,,,,,,,,,
1,0.0,405723.634896,0.000000,7.583585e+05,0.000000,69247.331249,0.000000,0.000000,108156.932364,951553.888033,0.000000,7.571291e+05,2.407699e+06,0.000000,3.197202e+06,2.085722e+05,0.000000,494024.599590,9.357667e+06
2,0.0,583637.809185,165551.643573,2.595070e+06,32409.891463,0.000000,0.000000,0.000000,118770.365673,480907.463277,0.000000,2.381060e+06,6.663384e+06,0.000000,3.346182e+05,1.260826e+06,0.000000,142828.453994,1.475906e+07
3,0.0,622.912438,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,20188.685897,186088.649532,1.002090e+05,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,3.071093e+05
4,0.0,199134.724691,209168.983266,0.000000e+00,0.000000,149534.092118,0.000000,0.000000,0.000000,7408.692072,6620.788829,5.918005e+05,3.341737e+04,19140.047384,8.182982e+04,0.000000e+00,0.000000,50447.136068,1.348502e+06
6,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,246042.663720,357210.178316,5.195147e+05,4.422149e+05,96338.238501,4.263169e+05,0.000000e+00,51997.178419,36784.370050,2.176419e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.0,0.000000,0.000000,0.000000e+00,23377.626629,0.000000,0.000000,2810.451354,23666.496671,31894.419371,34738.451389,4.472159e+05,0.000000e+00,0.000000,4.420455e+04,0.000000e+00,5711.847937,0.000000,6.136198e+05
19334,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,6557.719826,11728.990641,0.000000,65904.780306,7.050518e+05,0.000000e+00,47850.118461,0.000000e+00,0.000000e+00,0.000000,0.000000,8.370934e+05
19335,0.0,25954.684934,0.000000,0.000000e+00,0.000000,0.000000,96426.500298,26605.606151,107723.220355,66798.619897,37479.871764,2.706369e+05,0.000000e+00,47850.118461,0.000000e+00,0.000000e+00,264710.268016,0.000000,9.441858e+05
19336,0.0,0.000000,0.000000,0.000000e+00,0.000000,408828.637580,0.000000,0.000000,0.000000,0.000000,0.000000,6.241938e+04,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,4.712480e+05
19337,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8007.016491,8.754667e+03,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,1.676168e+04

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
CUSTNO,,,,,,,,,,,,,,,,,,,
1,0.000000,8.027014e+05,929676.672404,2.166887e+06,0.000000,69247.331249,0.000000,0.000000,181006.815190,3.824034e+06,747.380988,1.278370e+06,3.862975e+06,0.000000,6.904723e+06,2.085722e+05,0.000000,494024.599590,2.072297e+07
2,0.000000,1.112842e+06,451364.063577,4.076536e+06,32409.891463,236452.983657,0.000000,0.000000,467070.280225,1.273521e+06,0.000000,4.153922e+06,9.551356e+06,0.000000,1.157022e+06,2.391433e+06,0.000000,257966.143843,2.516190e+07
3,0.000000,2.272313e+03,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,4.873169e+04,450006.813477,2.783901e+05,0.000000e+00,0.000000,8.366903e+04,0.000000e+00,0.000000,0.000000,8.630699e+05
4,0.000000,3.499999e+05,512688.220398,1.166910e+05,5053.969564,286341.448899,0.000000,0.000000,0.000000,8.343084e+04,69500.442605,1.502106e+06,8.157779e+05,34193.895988,1.341885e+06,0.000000e+00,5983.754558,50447.136068,5.174100e+06
6,39405.980611,1.121592e+05,268490.733028,0.000000e+00,14384.374914,0.000000,0.000000,0.000000,0.000000,4.846771e+05,585534.073589,1.192411e+06,8.233104e+05,217772.617240,1.398969e+06,9.652073e+04,99069.380946,36784.370050,5.369490e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.000000,1.649401e+03,0.000000,0.000000e+00,23377.626629,0.000000,0.000000,2810.451354,48964.339866,1.592706e+05,64404.494066,1.197496e+06,0.000000e+00,0.000000,4.420455e+04,0.000000e+00,5711.847937,0.000000,1.547890e+06
19334,0.000000,0.000000e+00,0.000000,0.000000e+00,15453.483860,0.000000,0.000000,39831.742934,44122.088295,1.179315e+05,373136.163765,2.849299e+06,0.000000e+00,90984.412661,0.000000e+00,0.000000e+00,35503.610380,0.000000,3.566262e+06
19335,0.000000,8.896179e+04,0.000000,0.000000e+00,79697.212359,59922.685415,179784.875986,356411.435198,311825.428695,4.896131e+05,199811.022320,1.114446e+06,0.000000e+00,423604.215517,4.518127e+04,0.000000e+00,420926.153689,46726.013571,3.816911e+06
19336,0.000000,5.388042e+04,51350.686645,0.000000e+00,0.000000,417430.442422,0.000000,0.000000,0.000000,7.819874e+05,0.000000,5.993300e+05,3.654908e+05,24989.388683,1.647391e+06,0.000000e+00,0.000000,57908.307417,3.999758e+06
19337,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,41051.221232,4.768725e+04,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,8.873848e+04

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
CUSTNO,,,,,,,,,,,,,,,,,,,
1,267033.466216,8.626033e+05,1.085537e+06,2.166887e+06,0.000000,81868.361001,0.000000,0.000000,181006.815190,4.033315e+06,26319.187479,2.147943e+06,6.882280e+06,0.000000,1.191715e+07,1.795664e+06,0.000000,1.872037e+06,3.331965e+07
2,0.000000,1.824323e+06,4.513641e+05,6.643885e+06,32409.891463,236452.983657,0.000000,0.000000,596354.032984,1.404973e+06,0.000000,5.758386e+06,1.358354e+07,0.000000,4.880434e+06,3.810627e+06,0.000000,2.875441e+06,4.209819e+07
3,0.000000,1.039262e+04,0.000000e+00,0.000000e+00,27286.153172,0.000000,0.000000,0.000000,0.000000,7.251760e+04,706007.493630,5.786721e+05,0.000000e+00,0.000000,8.366903e+04,0.000000e+00,6812.722249,0.000000e+00,1.485358e+06
4,0.000000,5.799576e+05,5.126882e+05,4.887139e+05,5053.969564,528563.232022,0.000000,0.000000,0.000000,1.052929e+05,89858.485197,1.956093e+06,1.228433e+06,96124.559152,2.104719e+06,1.093370e+05,5983.754558,1.563942e+05,7.967213e+06
6,103751.394157,1.462881e+05,3.226088e+05,0.000000e+00,14384.374914,0.000000,0.000000,0.000000,0.000000,9.328709e+05,859698.142820,1.732042e+06,1.799548e+06,338689.871296,2.269728e+06,9.652073e+04,144805.456308,3.678437e+04,8.797720e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.000000,2.826257e+03,0.000000e+00,0.000000e+00,23377.626629,0.000000,0.000000,2810.451354,48964.339866,1.643426e+05,78886.088748,1.724698e+06,0.000000e+00,0.000000,4.420455e+04,0.000000e+00,5711.847937,0.000000e+00,2.095822e+06
19334,0.000000,1.588756e+04,0.000000e+00,0.000000e+00,18496.549269,0.000000,47149.645104,52004.790567,67123.778833,2.270144e+05,702808.789625,4.726624e+06,0.000000e+00,132622.006231,0.000000e+00,0.000000e+00,38682.880763,0.000000e+00,6.028415e+06
19335,0.000000,4.353105e+05,0.000000e+00,0.000000e+00,96636.943139,76495.754786,186756.878645,514629.518025,549797.718155,8.875110e+05,317623.570283,1.890101e+06,0.000000e+00,479541.588697,4.518127e+04,0.000000e+00,591743.809535,4.672601e+04,6.118056e+06
19336,0.000000,1.137236e+05,1.836693e+05,0.000000e+00,0.000000,675524.126597,0.000000,0.000000,23130.191602,7.929184e+05,0.000000,1.367299e+06,7.407396e+05,24989.388683,3.701780e+06,0.000000e+00,0.000000,9.871516e+04,7.722489e+06
19337,0.000000,1.353385e+03,0.000000e+00,0.000000e+00,19252.460491,0.000000,0.000000,0.000000,0.000000,1.740219e+04,245254.375211,3.477344e+05,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,33518.593463,0.000000e+00,6.645154e+05

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
CUSTNO,,,,,,,,,,,,,,,,,,,
1,267033.466216,1.680893e+06,1.278729e+06,7.529381e+06,0.000000,126427.256070,0.000000,0.000000,181006.815190,4.510241e+06,8.910603e+04,3.807123e+06,7.652280e+06,14207.650394,1.541476e+07,8.151613e+06,57778.973803,2.242824e+06,5.300341e+07
2,349551.026877,2.076765e+06,4.513641e+05,6.994484e+06,61140.375992,236452.983657,0.000000,0.000000,596354.032984,1.775768e+06,2.490751e+03,7.355623e+06,1.556554e+07,0.000000,6.008119e+06,3.844664e+06,0.000000,2.953739e+06,4.827205e+07
3,0.000000,1.113618e+04,0.000000e+00,0.000000e+00,27286.153172,0.000000,0.000000,0.000000,0.000000,1.244021e+05,8.578357e+05,7.833371e+05,0.000000e+00,0.000000,8.366903e+04,0.000000e+00,6812.722249,0.000000e+00,1.894479e+06
4,0.000000,6.655059e+05,5.126882e+05,4.887139e+05,5053.969564,605528.596231,0.000000,0.000000,0.000000,1.139838e+05,1.453624e+05,2.286312e+06,1.437657e+06,154933.441164,2.522210e+06,3.746529e+05,26714.234235,2.091595e+05,9.548475e+06
6,103751.394157,1.945802e+05,3.226088e+05,0.000000e+00,14384.374914,0.000000,0.000000,0.000000,0.000000,1.183339e+06,1.111870e+06,2.303857e+06,2.582697e+06,492905.823359,2.698937e+06,1.829230e+05,195543.015785,7.327289e+04,1.146067e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.000000,4.195970e+03,0.000000e+00,0.000000e+00,23377.626629,0.000000,0.000000,2810.451354,48964.339866,2.033920e+05,1.214580e+05,2.121771e+06,0.000000e+00,0.000000,4.420455e+04,0.000000e+00,5711.847937,0.000000e+00,2.575886e+06
19334,0.000000,6.879761e+04,0.000000e+00,0.000000e+00,36692.522804,0.000000,75261.376556,120831.240209,117939.292431,3.338724e+05,1.487852e+06,6.349036e+06,0.000000e+00,173851.168926,0.000000e+00,0.000000e+00,152781.587900,0.000000e+00,8.916915e+06
19335,0.000000,5.127189e+05,0.000000e+00,0.000000e+00,121824.001242,76495.754786,186756.878645,654083.647071,785151.986169,9.452692e+05,4.698921e+05,2.934840e+06,4.108861e+04,603732.639074,4.518127e+04,0.000000e+00,669627.874242,9.135290e+04,8.138015e+06
19336,152976.379377,2.397371e+05,1.836693e+05,0.000000e+00,0.000000,749613.416670,0.000000,0.000000,23130.191602,8.908137e+05,0.000000e+00,2.017329e+06,2.707191e+06,24989.388683,5.508685e+06,0.000000e+00,0.000000,9.871516e+04,1.259685e+07
19337,0.000000,2.136078e+03,0.000000e+00,0.000000e+00,19252.460491,0.000000,0.000000,0.000000,0.000000,6.467471e+04,4.396724e+05,6.425191e+05,0.000000e+00,0.000000,1.832318e+05,0.000000e+00,44474.478253,0.000000e+00,1.395961e+06

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
CUSTNO,,,,,,,,,,,,,,,,,,,
1,8.376127e+05,1.738679e+06,2.047993e+06,7.681230e+06,0.000000,529266.078727,0.000000,0.000000,1.810068e+05,4.774940e+06,1.354081e+05,5.234493e+06,8.999026e+06,14207.650394,1.924261e+07,8.636031e+06,69192.988578,2.544540e+06,6.266624e+07
2,2.099150e+06,2.343994e+06,8.243740e+05,9.098362e+06,151250.500454,236452.983657,0.000000,0.000000,1.679685e+06,2.267992e+06,2.490751e+03,8.724581e+06,2.417045e+07,0.000000,7.050482e+06,6.144794e+06,0.000000,2.953739e+06,6.774779e+07
3,0.000000e+00,1.129191e+04,0.000000e+00,0.000000e+00,27286.153172,0.000000,0.000000,0.000000,0.000000e+00,1.294956e+05,1.063939e+06,8.575524e+05,0.000000e+00,0.000000,8.366903e+04,0.000000e+00,6812.722249,0.000000e+00,2.180046e+06
4,0.000000e+00,6.987487e+05,5.126882e+05,4.887139e+05,5053.969564,637220.738679,0.000000,0.000000,0.000000e+00,1.614365e+05,1.678937e+05,3.146943e+06,1.518059e+06,163121.128100,3.162076e+06,4.087007e+05,26714.234235,2.091595e+05,1.130653e+07
6,1.037514e+05,3.300637e+05,3.226088e+05,0.000000e+00,14384.374914,0.000000,0.000000,0.000000,0.000000e+00,1.512901e+06,1.445667e+06,3.082756e+06,3.305316e+06,559204.820827,2.904951e+06,1.307675e+06,221004.304044,1.394848e+05,1.524977e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.000000e+00,4.195970e+03,0.000000e+00,0.000000e+00,23377.626629,0.000000,0.000000,2810.451354,4.896434e+04,2.237844e+05,1.650828e+05,2.906002e+06,0.000000e+00,0.000000,4.420455e+04,0.000000e+00,5711.847937,0.000000e+00,3.424134e+06
19334,0.000000e+00,8.644680e+04,0.000000e+00,0.000000e+00,36692.522804,0.000000,468187.719559,155774.518710,2.848559e+05,3.771670e+05,1.623994e+06,7.214310e+06,0.000000e+00,268807.070671,0.000000e+00,0.000000e+00,165076.582611,0.000000e+00,1.068131e+07
19335,0.000000e+00,5.552846e+05,0.000000e+00,0.000000e+00,149239.581562,118223.742343,186756.878645,954970.569024,9.391197e+05,1.013837e+06,6.452127e+05,3.945524e+06,4.108861e+04,897691.866818,1.013108e+05,0.000000e+00,682009.998837,1.158408e+05,1.034611e+07
19336,1.529764e+05,2.397371e+05,2.741709e+05,0.000000e+00,0.000000,870043.557973,0.000000,0.000000,1.829572e+05,9.602702e+05,0.000000e+00,2.437114e+06,3.378604e+06,35537.681463,6.705292e+06,2.456726e+05,0.000000,9.871516e+04,1.558109e+07
19337,0.000000e+00,2.136078e+03,0.000000e+00,0.000000e+00,19252.460491,0.000000,0.000000,1405.225677,0.000000e+00,6.467471e+04,5.850608e+05,9.611471e+05,0.000000e+00,0.000000,2.549871e+05,0.000000e+00,47359.445516,0.000000e+00,1.936023e+06

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
CUSTNO,,,,,,,,,,,,,,,,,,,
1,1.093448e+06,1.760671e+06,2.052578e+06,7.681230e+06,0.000000,6.164922e+05,0.000000,0.000000e+00,1.810068e+05,5.178473e+06,1.905848e+05,6.140115e+06,1.100747e+07,1.420765e+04,2.398988e+07,9.088070e+06,69192.988578,2.544540e+06,7.160796e+07
2,2.099150e+06,2.880159e+06,8.243740e+05,9.728523e+06,151250.500454,2.364530e+05,0.000000,0.000000e+00,1.679685e+06,2.393479e+06,7.473291e+03,9.635851e+06,2.786698e+07,1.730791e+05,8.713823e+06,6.331079e+06,0.000000,4.662234e+06,7.738359e+07
3,0.000000e+00,1.349111e+04,0.000000e+00,0.000000e+00,27286.153172,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,1.294956e+05,1.279703e+06,9.523007e+05,0.000000e+00,0.000000e+00,8.366903e+04,0.000000e+00,6812.722249,0.000000e+00,2.492758e+06
4,0.000000e+00,8.110399e+05,5.343289e+05,4.887139e+05,5053.969564,6.681486e+05,0.000000,7.231205e+04,0.000000e+00,2.945668e+05,2.485292e+05,3.834783e+06,1.812533e+06,1.890137e+05,3.694420e+06,4.087007e+05,26714.234235,2.091595e+05,1.329802e+07
6,1.633656e+05,4.719121e+05,3.679991e+05,0.000000e+00,14384.374914,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,1.639400e+06,1.556897e+06,3.477954e+06,4.350941e+06,6.395924e+05,3.797281e+06,1.307675e+06,221004.304044,1.394848e+05,1.814789e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.000000e+00,4.195970e+03,0.000000e+00,0.000000e+00,23377.626629,0.000000e+00,0.000000,2.810451e+03,4.896434e+04,2.831333e+05,1.895770e+05,3.385642e+06,0.000000e+00,0.000000e+00,4.420455e+04,0.000000e+00,5711.847937,0.000000e+00,3.987617e+06
19334,0.000000e+00,9.854240e+04,0.000000e+00,0.000000e+00,36692.522804,0.000000e+00,468187.719559,1.973801e+05,2.932457e+05,4.384056e+05,1.726403e+06,7.664880e+06,0.000000e+00,3.698686e+05,0.000000e+00,0.000000e+00,168068.459890,0.000000e+00,1.146167e+07
19335,0.000000e+00,6.960334e+05,6.279455e+05,0.000000e+00,218828.854792,2.676439e+05,211650.201796,1.166457e+06,1.218710e+06,1.158721e+06,7.619257e+05,4.757233e+06,9.628908e+04,1.014329e+06,1.013108e+05,0.000000e+00,770230.486877,1.158408e+05,1.318315e+07
19336,3.634447e+05,2.397371e+05,5.006641e+05,0.000000e+00,0.000000,1.324441e+06,0.000000,0.000000e+00,1.829572e+05,9.602702e+05,0.000000e+00,2.662825e+06,3.835919e+06,3.553768e+04,8.843035e+06,2.456726e+05,0.000000,9.871516e+04,1.929322e+07
19337,0.000000e+00,2.136078e+03,0.000000e+00,0.000000e+00,19252.460491,0.000000e+00,0.000000,1.405226e+03,0.000000e+00,9.955154e+04,9.027176e+05,1.272548e+06,0.000000e+00,0.000000e+00,2.549871e+05,0.000000e+00,48526.277655,0.000000e+00,2.601124e+06

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
CUSTNO,,,,,,,,,,,,,,,,,,,
1,1.093448e+06,1.760671e+06,3.011604e+06,7.808240e+06,0.000000,7.727253e+05,0.000000,0.000000e+00,1.810068e+05,5.283236e+06,1.927190e+05,6.620455e+06,1.157111e+07,1.420765e+04,2.888486e+07,1.105613e+07,69192.988578,2.544540e+06,8.086416e+07
2,2.099150e+06,3.828941e+06,8.243740e+05,1.488718e+07,151250.500454,2.364530e+05,0.000000,0.000000e+00,1.763678e+06,2.792050e+06,9.422361e+03,1.052947e+07,3.099952e+07,2.172402e+05,1.315307e+07,7.204342e+06,0.000000,4.760364e+06,9.345652e+07
3,0.000000e+00,1.584482e+04,0.000000e+00,0.000000e+00,29619.169986,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,2.113077e+05,1.432568e+06,1.109833e+06,0.000000e+00,0.000000e+00,8.366903e+04,0.000000e+00,6812.722249,0.000000e+00,2.889655e+06
4,0.000000e+00,8.814159e+05,7.183303e+05,4.887139e+05,8624.499645,8.440781e+05,0.000000,7.231205e+04,0.000000e+00,3.428644e+05,3.011473e+05,4.482306e+06,1.847989e+06,3.001525e+05,4.689369e+06,4.732095e+05,26714.234235,2.091595e+05,1.568639e+07
6,3.394688e+05,5.071001e+05,5.574123e+05,0.000000e+00,14384.374914,0.000000e+00,0.000000,1.261456e+03,0.000000e+00,2.313961e+06,1.741137e+06,4.069102e+06,4.896972e+06,8.005700e+05,4.977027e+06,1.307675e+06,228634.552963,1.793226e+05,2.193403e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.000000e+00,4.195970e+03,0.000000e+00,0.000000e+00,23377.626629,0.000000e+00,0.000000,2.810451e+03,4.896434e+04,2.851446e+05,2.081224e+05,3.604158e+06,0.000000e+00,0.000000e+00,4.420455e+04,0.000000e+00,5711.847937,0.000000e+00,4.226690e+06
19334,0.000000e+00,9.854240e+04,0.000000e+00,0.000000e+00,36692.522804,0.000000e+00,495839.391124,2.005338e+05,5.549205e+05,4.384056e+05,1.763757e+06,7.701056e+06,0.000000e+00,3.698686e+05,2.046101e+05,0.000000e+00,168068.459890,0.000000e+00,1.203229e+07
19335,0.000000e+00,7.817085e+05,6.279455e+05,0.000000e+00,363881.639315,2.676439e+05,249937.131654,1.303430e+06,1.497394e+06,1.207412e+06,8.791769e+05,5.405590e+06,9.628908e+04,1.062696e+06,1.013108e+05,0.000000e+00,797608.546687,1.158408e+05,1.475787e+07
19336,7.713043e+05,4.982924e+05,7.522048e+05,0.000000e+00,0.000000,1.362687e+06,0.000000,0.000000e+00,2.573710e+05,1.335860e+06,0.000000e+00,3.151615e+06,4.090319e+06,3.553768e+04,1.411369e+07,2.456726e+05,0.000000,2.971506e+05,2.691170e+07
19337,0.000000e+00,2.136078e+03,0.000000e+00,0.000000e+00,24314.092622,0.000000e+00,0.000000,1.405226e+03,0.000000e+00,9.955154e+04,1.393201e+06,1.942370e+06,0.000000e+00,0.000000e+00,2.549871e+05,0.000000e+00,49498.226029,0.000000e+00,3.767464e+06

In [34]:
df_li = [year2014_q1, year2014_q2, year2014_q3, year2014_q4, year2015_q1, year2015_q2, year2015_q3, year2015_q4]
df_li[0]

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가,purchase_sum
CUSTNO,,,,,,,,,,,,,,,,,,,
1,0.0,405723.634896,0.000000,7.583585e+05,0.000000,69247.331249,0.000000,0.000000,108156.932364,951553.888033,0.000000,7.571291e+05,2.407699e+06,0.000000,3.197202e+06,2.085722e+05,0.000000,494024.599590,9.357667e+06
2,0.0,583637.809185,165551.643573,2.595070e+06,32409.891463,0.000000,0.000000,0.000000,118770.365673,480907.463277,0.000000,2.381060e+06,6.663384e+06,0.000000,3.346182e+05,1.260826e+06,0.000000,142828.453994,1.475906e+07
3,0.0,622.912438,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,20188.685897,186088.649532,1.002090e+05,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,3.071093e+05
4,0.0,199134.724691,209168.983266,0.000000e+00,0.000000,149534.092118,0.000000,0.000000,0.000000,7408.692072,6620.788829,5.918005e+05,3.341737e+04,19140.047384,8.182982e+04,0.000000e+00,0.000000,50447.136068,1.348502e+06
6,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,246042.663720,357210.178316,5.195147e+05,4.422149e+05,96338.238501,4.263169e+05,0.000000e+00,51997.178419,36784.370050,2.176419e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.0,0.000000,0.000000,0.000000e+00,23377.626629,0.000000,0.000000,2810.451354,23666.496671,31894.419371,34738.451389,4.472159e+05,0.000000e+00,0.000000,4.420455e+04,0.000000e+00,5711.847937,0.000000,6.136198e+05
19334,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,6557.719826,11728.990641,0.000000,65904.780306,7.050518e+05,0.000000e+00,47850.118461,0.000000e+00,0.000000e+00,0.000000,0.000000,8.370934e+05
19335,0.0,25954.684934,0.000000,0.000000e+00,0.000000,0.000000,96426.500298,26605.606151,107723.220355,66798.619897,37479.871764,2.706369e+05,0.000000e+00,47850.118461,0.000000e+00,0.000000e+00,264710.268016,0.000000,9.441858e+05
19336,0.0,0.000000,0.000000,0.000000e+00,0.000000,408828.637580,0.000000,0.000000,0.000000,0.000000,0.000000,6.241938e+04,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,4.712480e+05
19337,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8007.016491,8.754667e+03,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,1.676168e+04

## 고객별 중요 상품군 뽑아보기 (매출로만)

In [172]:
year2014_q1.loc[1].sort_values(ascending = False)[1:3]

의류/이미용_중가    3.197202e+06
의류/이미용_고가    2.407699e+06
Name: 1, dtype: float64

In [67]:
year2014_q1.loc[1].sort_values(ascending = False)[1:][:2]

의류/이미용_중가    3.197202e+06
의류/이미용_고가    2.407699e+06
Name: 1, dtype: float64

In [189]:
year2014_q1.drop('purchase_sum', axis=1)

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가
CUSTNO,,,,,,,,,,,,,,,,,,
1,0.0,405723.634896,0.000000,7.583585e+05,0.000000,69247.331249,0.000000,0.000000,108156.932364,951553.888033,0.000000,7.571291e+05,2.407699e+06,0.000000,3.197202e+06,2.085722e+05,0.000000,494024.599590
2,0.0,583637.809185,165551.643573,2.595070e+06,32409.891463,0.000000,0.000000,0.000000,118770.365673,480907.463277,0.000000,2.381060e+06,6.663384e+06,0.000000,3.346182e+05,1.260826e+06,0.000000,142828.453994
3,0.0,622.912438,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,20188.685897,186088.649532,1.002090e+05,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000
4,0.0,199134.724691,209168.983266,0.000000e+00,0.000000,149534.092118,0.000000,0.000000,0.000000,7408.692072,6620.788829,5.918005e+05,3.341737e+04,19140.047384,8.182982e+04,0.000000e+00,0.000000,50447.136068
6,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,246042.663720,357210.178316,5.195147e+05,4.422149e+05,96338.238501,4.263169e+05,0.000000e+00,51997.178419,36784.370050
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0.0,0.000000,0.000000,0.000000e+00,23377.626629,0.000000,0.000000,2810.451354,23666.496671,31894.419371,34738.451389,4.472159e+05,0.000000e+00,0.000000,4.420455e+04,0.000000e+00,5711.847937,0.000000
19334,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,6557.719826,11728.990641,0.000000,65904.780306,7.050518e+05,0.000000e+00,47850.118461,0.000000e+00,0.000000e+00,0.000000,0.000000
19335,0.0,25954.684934,0.000000,0.000000e+00,0.000000,0.000000,96426.500298,26605.606151,107723.220355,66798.619897,37479.871764,2.706369e+05,0.000000e+00,47850.118461,0.000000e+00,0.000000e+00,264710.268016,0.000000
19336,0.0,0.000000,0.000000,0.000000e+00,0.000000,408828.637580,0.000000,0.000000,0.000000,0.000000,0.000000,6.241938e+04,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000
19337,0.0,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8007.016491,8.754667e+03,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000

In [ ]:
13380

In [186]:
year2014_q1.loc[13380].sort_values(ascending = False)

식품/생활_고가          17947.556545
purchase_sum      17947.556545
가구인테리어/잡화_중가          0.000000
식품/생활_중가              0.000000
침구/주방_중가              0.000000
침구/주방_저가              0.000000
침구/주방_고가              0.000000
의류/이미용_중가             0.000000
의류/이미용_저가             0.000000
의류/이미용_고가             0.000000
식품/생활_저가              0.000000
가전/레저취미/멀티샵_고가        0.000000
가구인테리어/잡화_저가          0.000000
교육문화/아동_중가            0.000000
교육문화/아동_저가            0.000000
교육문화/아동_고가            0.000000
가전/레저취미/멀티샵_중가        0.000000
가전/레저취미/멀티샵_저가        0.000000
가구인테리어/잡화_고가          0.000000
Name: 13380, dtype: float64

In [191]:
year2014_q1.loc[1].sort_values(ascending = False)[:2]

purchase_sum    9.357667e+06
의류/이미용_중가       3.197202e+06
Name: 1, dtype: float64

In [62]:
year2014_q1.index

Int64Index([    1,     2,     3,     4,     6,     7,     8,     9,    10,
               11,
            ...
            19328, 19329, 19330, 19331, 19332, 19333, 19334, 19335, 19336,
            19337],
           dtype='int64', name='CUSTNO', length=18866)

In [71]:
year2014_q1.loc[1].sort_values(ascending = False)[1:3].index[1]

'의류/이미용_고가'

In [60]:
dic = {}

# 중요 카테고리_1
dic[f'{year2014_q1.loc[1].sort_values(ascending = False)[1:3].index[0]}'] = year2014_q1.loc[1].sort_values(ascending = False)[1:][0]

In [61]:
dic

{'의류/이미용_중가': 3197202.122284048}

In [ ]:
'중요 카테고리 top_1', '중요 카테고리 top_2'

In [192]:
df_li = [year2014_q1, year2014_q2, year2014_q3, year2014_q4, year2015_q1, year2015_q2, year2015_q3, year2015_q4]

# 빈 데이터 프레임
total_df = pd.DataFrame(index = year2014_q1.index)

for i in range(8):
    quater = i+1
    df = df_li[i]
    df = df.drop('purchase_sum', axis=1)
    
    # 고객 번호별로 중요 상품군 추가됨
    for cust in df.index:
        # 고객 번호 별로 담겨질 딕셔너리
        dic_1 = {} # top1
        dic_2 = {} # top2
        
        rank_top2 = df.loc[cust].sort_values(ascending = False)[:2] 
        
        # 딕셔너리로 차례대로 담기 (해당 카테고리 : 구매금액)
        dic_1[f'{rank_top2.index[0]}'] = rank_top2[0]
        dic_2[f'{rank_top2.index[1]}'] = rank_top2[1]
        
        # total_df에 추가
        column_top1 = f'{quater}분기 중요 카테고리 top_1'
        column_top2 = f'{quater}분기 중요 카테고리 top_2'
        
        total_df.loc[cust, column_top1] = [dic_1]
        total_df.loc[cust, column_top2] = [dic_2]
total_df

,1분기 중요 카테고리 top_1,1분기 중요 카테고리 top_2,2분기 중요 카테고리 top_1,2분기 중요 카테고리 top_2,3분기 중요 카테고리 top_1,3분기 중요 카테고리 top_2,4분기 중요 카테고리 top_1,4분기 중요 카테고리 top_2,5분기 중요 카테고리 top_1,5분기 중요 카테고리 top_2,6분기 중요 카테고리 top_1,6분기 중요 카테고리 top_2,7분기 중요 카테고리 top_1,7분기 중요 카테고리 top_2,8분기 중요 카테고리 top_1,8분기 중요 카테고리 top_2
CUSTNO,,,,,,,,,,,,,,,,
1,{'의류/이미용_중가': 3197202.122284048},{'의류/이미용_고가': 2407699.1285152645},{'의류/이미용_중가': 3707521.037695056},{'식품/생활_고가': 2872479.795491419},{'의류/이미용_중가': 5012430.483498257},{'의류/이미용_고가': 3019305.1613326394},{'침구/주방_고가': 6355948.699891901},{'가전/레저취미/멀티샵_고가': 5362493.79361085},{'의류/이미용_중가': 3827846.869022515},{'식품/생활_중가': 1427370.6711798671},{'의류/이미용_중가': 4747265.58615696},{'의류/이미용_고가': 2008447.9257823203},{'의류/이미용_중가': 4894986.851878235},{'침구/주방_고가': 1968065.340072287},{'의류/이미용_중가': 2629269.026835497},{'침구/주방_중가': 625313.0312615287}
2,[{'의류/이미용_고가': 6663384.02224353}],[{'가전/레저취미/멀티샵_고가': 2595070.108576713}],[{'의류/이미용_고가': 2887971.9003850822}],[{'식품/생활_중가': 1772862.2568761252}],[{'의류/이미용_고가': 4032181.494005245}],[{'의류/이미용_중가': 3723412.487666992}],[{'의류/이미용_고가': 1981999.3053619056}],[{'식품/생활_중가': 1597236.8476083712}],[{'의류/이미용_고가': 8604908.281508606}],[{'침구/주방_고가': 2300129.741046512}],[{'의류/이미용_고가': 3696531.4226418887}],[{'침구/주방_중가': 1708494.7526076774}],[{'가전/레저취미/멀티샵_고가': 5158661.70412413}],[{'의류/이미용_중가': 4439250.13515403}],[{'의류/이미용_고가': 4845373.86259573}],[{'의류/이미용_중가': 2311184.722988136}]
3,[{'식품/생활_저가': 186088.6495317848}],[{'식품/생활_중가': 100209.02890246354}],[{'식품/생활_저가': 263918.16394483094}],[{'식품/생활_중가': 178181.04322254387}],[{'식품/생활_중가': 300282.03802015947}],[{'식품/생활_저가': 256000.6801535801}],[{'식품/생활_중가': 204664.99395321944}],[{'식품/생활_저가': 151828.18998257397}],[{'식품/생활_저가': 206103.08726348507}],[{'식품/생활_중가': 74215.24613389547}],[{'식품/생활_저가': 215763.9086452532}],[{'식품/생활_중가': 94748.33651823708}],[{'식품/생활_중가': 157532.55063700263}],[{'식품/생활_저가': 152865.6084696432}],[{'식품/생활_저가': 145628.2134335323}],[{'식품/생활_중가': 108123.3843828506}]
4,[{'식품/생활_중가': 591800.5290698201}],[{'가구인테리어/잡화_중가': 209168.9832659017}],[{'의류/이미용_중가': 1260055.556995324}],[{'식품/생활_중가': 910305.3016598468}],[{'의류/이미용_중가': 762833.2301476472}],[{'식품/생활_중가': 453987.62623594346}],[{'의류/이미용_중가': 417491.4229120608}],[{'식품/생활_중가': 330218.2083646532}],[{'식품/생활_중가': 860631.6226465153}],[{'의류/이미용_중가': 639866.0217657617}],[{'식품/생활_중가': 687839.8188862434}],[{'의류/이미용_중가': 532344.1886708332}],[{'의류/이미용_중가': 994949.191461714}],[{'식품/생활_중가': 647522.988938108}],[{'식품/생활_중가': 653999.7448042707}],[{'의류/이미용_중가': 435737.6180935461}]
6,[{'식품/생활_중가': 519514.69985476224}],[{'의류/이미용_고가': 442214.8638972118}],[{'의류/이미용_중가': 972652.4468838406}],[{'식품/생활_중가': 672896.7673163582}],[{'의류/이미용_고가': 976237.8655630948}],[{'의류/이미용_중가': 870758.6051527484}],[{'의류/이미용_고가': 783148.8303673912}],[{'식품/생활_중가': 571815.7248140553}],[{'침구/주방_고가': 1124752.0784446886}],[{'식품/생활_중가': 778899.1288893034}],[{'의류/이미용_고가': 1045624.3165410073}],[{'의류/이미용_중가': 892330.1803024655}],[{'의류/이미용_중가': 1179745.8198901752}],[{'식품/생활_고가': 674561.2925821822}],[{'의류/이미용_고가': 801227.8170075619}],[{'식품/생활_중가': 747108.1097935721}]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,[{'식품/생활_중가': 447215.90814877686}],[{'의류/이미용_중가': 44204.55141289422}],[{'식품/생활_중가': 750280.4272318352}],[{'식품/생활_고가': 127376.23012714808}],[{'식품/생활_중가': 527201.9642398998}],[{'식품/생활_저가': 14481.594682257411}],[{'식품/생활_중가': 397072.7860070866}],[{'식품/생활_저가': 42571.91032308379}],[{'식품/생활_중가': 784230.7011192905}],[{'식품/생활_저가': 43624.7913963819}],[{'식품/생활_중가': 479640.255579298}],[{'식품/생활_고가': 59348.92480649536}],[{'식품/생활_중가': 218515.76517987612}],[{'식품/생활_저가': 18545.40691812642}],[{'식품/생활_중가': 507607.8050355344}],[{'식품/생활_저가': 28544.00259200446}]
19334,[{'식품/생활_중가': 705051.8180748143}],[{'식품/생활_저가': 65904.78030565097}],[{'식품/생활_중가': 2144247.647584814}],[{'식품/생활_저가': 307231.3834592681}],[{'식품/생활_중가': 1877324.941140104}],[{'식품/생활_저가': 329672.6258598125}],[{'식품/생활_중가': 1622411.8572099083}],[{'식품/생활_저가': 785042.764202117}],[{'식품/생활_중가': 865274.1886279666}],[{'교육문화/아동_고가': 392926.34300370846}],[{'식품/생활_중가': 450569.72043941455}],[{'식품/생활_저가': 102409.13247577766}],[{'교육문화/아동_중가': 261674.8948955477}],[{'의류/이미용_중가': 204610.14219829603}],[{'교육문화/아동_고가': 135979.05188398962}],[{'교육문화/아동_중가': 101631.02719622408}]
19335,[{'식품/생활_중가': 270636.8682743774}],[{'침구/주방_저가': 264710.2680157595}],[{'식품/생활_중가': 843808.922805592}],[{'식품/생활_고가': 422814.4312865259}],[{'식품/생활_중가': 775655.1849544768}],[{'식품/생활_고가': 397897.97783959575}],[{'식품/생활_중가': 1044738.5492114417}],[{'교육문화/아동_중가': 235354.26801380617}],[{'식품/생활_중가': 1010684.4205096288}],[{'교육문화/아동_저가': 300886.9219525443}],[{'식품/생활_중가': 811708.8484779363}],[{'가구인테리어/잡화_중가': 627945.5395399712}],[{'식품/생활_중가': 648357.531980953}],[{'교육문화/아동_중가': 278683.7630637583}],[{'식품/생활_중가': 878498.7927896515}],[{'교육문화/아동_중가': 583594.0058328143}]
19336,[{'가전/레저취미/멀티샵_중가': 408828.637580217}],[{'식품/생활_중가': 62419.37938978714}],[{'의류/이미용_중가': 1647390.862052776}],[{'식품/생활_고가': 781987.4054692313}],[{'의류/이미용_중가': 2054389.4277428912}],[{'식품/생활_중가': 767969.0530025541}],[{'의류/이미용_고가': 1966451.3768513591}],[{'의류/이미용_중가': 1806904.54130777}],[{'의류/이미용_중가': 1196606.926618811}],[{'의류/이미용_고가': 671412.8177875734}],[{'의류/이미용_중가': 2137743.657452226}],[{'의류/이미용_고가': 457314.6757013866}],[{'의류/이미용_중가': 5270653.6629561065}],[{'식품/생활_중가': 488790.2498388074}],[{'의류/이미용_중가': 2020662.1823263096}],[{'가구인테리어/잡화_저가': 615353.3616118222}]
19337,[{'식품/생활_중가': 8754.666949558004}],[{'식품/생활_저가': 8007.016490585627}],[{'식품/생활_중가': 38932.58803888598}],[{'식품/생활_저가': 33044.20474171714}],[{'식품/생활_중가': 300047.11557450047}],[{'식품/생활_저가': 204203.15397883824}],[{'식품/생활_중가': 294784.75288259063}],[{'식품/생활_저가': 194418.0337104276}],[{'식품/생활_중가': 318627.9981470684}],[{'식품/생활_저가': 145388.38470115038}],[{'식품/생활_저가': 317656.8499854395}],[{'식품/생활_중가': 311400.514790801}],[{'식품/생활_중가': 669822.6231851146}],[{'식품/생활_저가': 490483.62069853005}],[{'식품/생활_중가': 507607.8050355344}],[{'식품/생활_저가': 366279.8294214492}]

In [193]:
total_df.to_excel('분기별_고객별_구매금액top2_카테고리.xlsx')

In [219]:
total_df.to_csv('분기별_고객별_구매금액top2_카테고리.csv')

In [194]:
index = []
for i in total_df.index:
    if i == 1:
        pass
    else:
        df = total_df[['1분기 중요 카테고리 top_1']]
        name = df.loc[i][0][0].keys()
        cat_name = list(name)[0]
        if cat_name == 'purchase_sum':
            index.append(i)

index

[]

In [195]:
total_df.loc[index]

Empty DataFrame
Columns: [1분기 중요 카테고리 top_1, 1분기 중요 카테고리 top_2, 2분기 중요 카테고리 top_1, 2분기 중요 카테고리 top_2, 3분기 중요 카테고리 top_1, 3분기 중요 카테고리 top_2, 4분기 중요 카테고리 top_1, 4분기 중요 카테고리 top_2, 5분기 중요 카테고리 top_1, 5분기 중요 카테고리 top_2, 6분기 중요 카테고리 top_1, 6분기 중요 카테고리 top_2, 7분기 중요 카테고리 top_1, 7분기 중요 카테고리 top_2, 8분기 중요 카테고리 top_1, 8분기 중요 카테고리 top_2]
Index: []

# 분기별로 카테고리 횟수 보기

In [217]:
cate_df = pd.DataFrame(columns = total_df.columns, index = year2014_q1.columns[:-1])

for i in total_df.columns:
    df = total_df[[i]]
#     list(df.loc[1][0].keys())[0]
#     list(df.loc[19336][0][0].keys())[0]
    # 분기별 카테고리 초기화
    category = {}
    for cust in total_df.index:
        if cust == 1:
            name = total_df.loc[cust, i].keys()
            cat_name = list(name)[0]
            
        else:
            name = df.loc[cust][0][0].keys()
            cat_name = list(name)[0]
        
        # category 안에 있으면 +1, 없었으면 1
        if cat_name in category.keys():
            category[cat_name] += 1
        else:
            category[cat_name] = 1
    
    print(f'######## {i} ########')
    print(len(category))

    print(sorted(category.items()))
    print()
    
    # 데이터 프레임에 추가
    for cat, val in category.items():
        cate_df.loc[cat, i] = val
display(cate_df)

######## 1분기 중요 카테고리 top_1 ########
18
[('가구인테리어/잡화_고가', 947), ('가구인테리어/잡화_저가', 72), ('가구인테리어/잡화_중가', 335), ('가전/레저취미/멀티샵_고가', 419), ('가전/레저취미/멀티샵_저가', 28), ('가전/레저취미/멀티샵_중가', 541), ('교육문화/아동_고가', 9), ('교육문화/아동_저가', 21), ('교육문화/아동_중가', 304), ('식품/생활_고가', 628), ('식품/생활_저가', 244), ('식품/생활_중가', 10126), ('의류/이미용_고가', 976), ('의류/이미용_저가', 345), ('의류/이미용_중가', 3627), ('침구/주방_고가', 210), ('침구/주방_저가', 4), ('침구/주방_중가', 30)]

######## 1분기 중요 카테고리 top_2 ########
18
[('가구인테리어/잡화_고가', 618), ('가구인테리어/잡화_저가', 211), ('가구인테리어/잡화_중가', 769), ('가전/레저취미/멀티샵_고가', 326), ('가전/레저취미/멀티샵_저가', 150), ('가전/레저취미/멀티샵_중가', 994), ('교육문화/아동_고가', 36), ('교육문화/아동_저가', 50), ('교육문화/아동_중가', 637), ('식품/생활_고가', 2267), ('식품/생활_저가', 4194), ('식품/생활_중가', 3163), ('의류/이미용_고가', 1361), ('의류/이미용_저가', 1188), ('의류/이미용_중가', 2453), ('침구/주방_고가', 305), ('침구/주방_저가', 50), ('침구/주방_중가', 94)]

######## 2분기 중요 카테고리 top_1 ########
18
[('가구인테리어/잡화_고가', 955), ('가구인테리어/잡화_저가', 65), ('가구인테리어/잡화_중가', 279), ('가전/레저취미/멀티샵_고가', 381), ('가전/레저취미/멀티샵_저가', 25), ('가전/레저취미/멀티샵_중가', 427), ('교육문화/아동_고가', 9), ('교육문화/아동_저가', 19), ('교육문화/아동_중가', 286), ('식품/생활_고가', 625), ('식품/생활_저가', 267), ('식품/생활_중가', 10227), ('의류/이미용_고가', 1005), ('의류/이미용_저가', 330), ('의류/이미용_중가', 3697), ('침구/주방_고가', 219), ('침구/주방_저가', 5), ('침구/주방_중가', 45)]

######## 2분기 중요 카테고리 top_2 ########
18
[('가구인테리어/잡화_고가', 609), ('가구인테리어/잡화_저가', 166), ('가구인테리어/잡화_중가', 693), ('가전/레저취미/멀티샵_고가', 381), ('가전/레저취미/멀티샵_저가', 145), ('가전/레저취미/멀티샵_중가', 947), ('교육문화/아동_고가', 28), ('교육문화/아동_저가', 58), ('교육문화/아동_중가', 583), ('식품/생활_고가', 2536), ('식품/생활_저가', 4162), ('식품/생활_중가', 2951), ('의류/이미용_고가', 1428), ('의류/이미용_저가', 1296), ('의류/이미용_중가', 2459), ('침구/주방_고가', 292), ('침구/주방_저가', 40), ('침구/주방_중가', 92)]

######## 3분기 중요 카테고리 top_1 ########
18
[('가구인테리어/잡화_고가', 911), ('가구인테리어/잡화_저가', 69), ('가구인테리어/잡화_중가', 260), ('가전/레저취미/멀티샵_고가', 372), ('가전/레저취미/멀티샵_저가', 18), ('가전/레저취미/멀티샵_중가', 471), ('교육문화/아동_고가', 7), ('교육문화/아동_저가', 18), ('교육문화/아동_중가', 310), ('식품/생활_고가', 703), ('식품/생활_저가', 270), ('식품/생활_중가', 10208), ('의류/이미용_고가', 1017), ('의류/이미용_저가', 313), ('의류/이미용_중가', 3696), ('침구/주방_고가', 177), ('침구/주방_저가', 4), ('침구/주방_중가', 42)]

######## 3분기 중요 카테고리 top_2 ########
18
[('가구인테리어/잡화_고가', 601), ('가구인테리어/잡화_저가', 208), ('가구인테리어/잡화_중가', 744), ('가전/레저취미/멀티샵_고가', 323), ('가전/레저취미/멀티샵_저가', 126), ('가전/레저취미/멀티샵_중가', 956), ('교육문화/아동_고가', 26), ('교육문화/아동_저가', 63), ('교육문화/아동_중가', 634), ('식품/생활_고가', 2236), ('식품/생활_저가', 4284), ('식품/생활_중가', 3117), ('의류/이미용_고가', 1418), ('의류/이미용_저가', 1179), ('의류/이미용_중가', 2513), ('침구/주방_고가', 303), ('침구/주방_저가', 35), ('침구/주방_중가', 100)]

######## 4분기 중요 카테고리 top_1 ########
18
[('가구인테리어/잡화_고가', 1003), ('가구인테리어/잡화_저가', 45), ('가구인테리어/잡화_중가', 286), ('가전/레저취미/멀티샵_고가', 385), ('가전/레저취미/멀티샵_저가', 28), ('가전/레저취미/멀티샵_중가', 529), ('교육문화/아동_고가', 7), ('교육문화/아동_저가', 14), ('교육문화/아동_중가', 268), ('식품/생활_고가', 645), ('식품/생활_저가', 208), ('식품/생활_중가', 10500), ('의류/이미용_고가', 917), ('의류/이미용_저가', 448), ('의류/이미용_중가', 3339), ('침구/주방_고가', 199), ('침구/주방_저가', 3), ('침구/주방_중가', 42)]

######## 4분기 중요 카테고리 top_2 ########
18
[('가구인테리어/잡화_고가', 654), ('가구인테리어/잡화_저가', 138), ('가구인테리어/잡화_중가', 665), ('가전/레저취미/멀티샵_고가', 404), ('가전/레저취미/멀티샵_저가', 112), ('가전/레저취미/멀티샵_중가', 907), ('교육문화/아동_고가', 27), ('교육문화/아동_저가', 51), ('교육문화/아동_중가', 561), ('식품/생활_고가', 2962), ('식품/생활_저가', 4203), ('식품/생활_중가', 3097), ('의류/이미용_고가', 1189), ('의류/이미용_저가', 1221), ('의류/이미용_중가', 2243), ('침구/주방_고가', 314), ('침구/주방_저가', 45), ('침구/주방_중가', 73)]

######## 5분기 중요 카테고리 top_1 ########
18
[('가구인테리어/잡화_고가', 1038), ('가구인테리어/잡화_저가', 51), ('가구인테리어/잡화_중가', 328), ('가전/레저취미/멀티샵_고가', 395), ('가전/레저취미/멀티샵_저가', 31), ('가전/레저취미/멀티샵_중가', 464), ('교육문화/아동_고가', 14), ('교육문화/아동_저가', 11), ('교육문화/아동_중가', 285), ('식품/생활_고가', 667), ('식품/생활_저가', 269), ('식품/생활_중가', 10318), ('의류/이미용_고가', 945), ('의류/이미용_저가', 471), ('의류/이미용_중가', 3359), ('침구/주방_고가', 184), ('침구/주방_저가', 2), ('침구/주방_중가', 34)]

######## 5분기 중요 카테고리 top_2 ########
18
[('가구인테리어/잡화_고가', 647), ('가구인테리어/잡화_저가', 176), ('가구인테리어/잡화_중가', 714), ('가전/레저취미/멀티샵_고가', 349), ('가전/레저취미/멀티샵_저가', 62), ('가전/레저취미/멀티샵_중가', 843), ('교육문화/아동_고가', 66), ('교육문화/아동_저가', 28), ('교육문화/아동_중가', 504), ('식품/생활_고가', 2337), ('식품/생활_저가', 4700), ('식품/생활_중가', 3239), ('의류/이미용_고가', 1311), ('의류/이미용_저가', 1237), ('의류/이미용_중가', 2246), ('침구/주방_고가', 310), ('침구/주방_저가', 13), ('침구/주방_중가', 84)]

######## 6분기 중요 카테고리 top_1 ########
18
[('가구인테리어/잡화_고가', 1086), ('가구인테리어/잡화_저가', 42), ('가구인테리어/잡화_중가', 258), ('가전/레저취미/멀티샵_고가', 358), ('가전/레저취미/멀티샵_저가', 22), ('가전/레저취미/멀티샵_중가', 313), ('교육문화/아동_고가', 19), ('교육문화/아동_저가', 8), ('교육문화/아동_중가', 254), ('식품/생활_고가', 698), ('식품/생활_저가', 308), ('식품/생활_중가', 10415), ('의류/이미용_고가', 839), ('의류/이미용_저가', 418), ('의류/이미용_중가', 3595), ('침구/주방_고가', 195), ('침구/주방_저가', 1), ('침구/주방_중가', 37)]

######## 6분기 중요 카테고리 top_2 ########
18
[('가구인테리어/잡화_고가', 644), ('가구인테리어/잡화_저가', 111), ('가구인테리어/잡화_중가', 668), ('가전/레저취미/멀티샵_고가', 408), ('가전/레저취미/멀티샵_저가', 75), ('가전/레저취미/멀티샵_중가', 777), ('교육문화/아동_고가', 76), ('교육문화/아동_저가', 44), ('교육문화/아동_중가', 526), ('식품/생활_고가', 2562), ('식품/생활_저가', 4680), ('식품/생활_중가', 2960), ('의류/이미용_고가', 1433), ('의류/이미용_저가', 1252), ('의류/이미용_중가', 2288), ('침구/주방_고가', 271), ('침구/주방_저가', 14), ('침구/주방_중가', 77)]

######## 7분기 중요 카테고리 top_1 ########
17
[('가구인테리어/잡화_고가', 1079), ('가구인테리어/잡화_저가', 46), ('가구인테리어/잡화_중가', 254), ('가전/레저취미/멀티샵_고가', 377), ('가전/레저취미/멀티샵_저가', 22), ('가전/레저취미/멀티샵_중가', 432), ('교육문화/아동_고가', 20), ('교육문화/아동_저가', 11), ('교육문화/아동_중가', 254), ('식품/생활_고가', 724), ('식품/생활_저가', 293), ('식품/생활_중가', 10416), ('의류/이미용_고가', 944), ('의류/이미용_저가', 358), ('의류/이미용_중가', 3408), ('침구/주방_고가', 182), ('침구/주방_중가', 46)]

######## 7분기 중요 카테고리 top_2 ########
18
[('가구인테리어/잡화_고가', 649), ('가구인테리어/잡화_저가', 160), ('가구인테리어/잡화_중가', 632), ('가전/레저취미/멀티샵_고가', 329), ('가전/레저취미/멀티샵_저가', 75), ('가전/레저취미/멀티샵_중가', 879), ('교육문화/아동_고가', 103), ('교육문화/아동_저가', 39), ('교육문화/아동_중가', 560), ('식품/생활_고가', 2399), ('식품/생활_저가', 4645), ('식품/생활_중가', 3034), ('의류/이미용_고가', 1393), ('의류/이미용_저가', 1211), ('의류/이미용_중가', 2342), ('침구/주방_고가', 314), ('침구/주방_저가', 17), ('침구/주방_중가', 85)]

######## 8분기 중요 카테고리 top_1 ########
18
[('가구인테리어/잡화_고가', 1134), ('가구인테리어/잡화_저가', 62), ('가구인테리어/잡화_중가', 258), ('가전/레저취미/멀티샵_고가', 397), ('가전/레저취미/멀티샵_저가', 24), ('가전/레저취미/멀티샵_중가', 480), ('교육문화/아동_고가', 14), ('교육문화/아동_저가', 17), ('교육문화/아동_중가', 264), ('식품/생활_고가', 719), ('식품/생활_저가', 210), ('식품/생활_중가', 10380), ('의류/이미용_고가', 895), ('의류/이미용_저가', 424), ('의류/이미용_중가', 3312), ('침구/주방_고가', 224), ('침구/주방_저가', 6), ('침구/주방_중가', 46)]

######## 8분기 중요 카테고리 top_2 ########
18
[('가구인테리어/잡화_고가', 687), ('가구인테리어/잡화_저가', 142), ('가구인테리어/잡화_중가', 651), ('가전/레저취미/멀티샵_고가', 409), ('가전/레저취미/멀티샵_저가', 96), ('가전/레저취미/멀티샵_중가', 884), ('교육문화/아동_고가', 58), ('교육문화/아동_저가', 32), ('교육문화/아동_중가', 543), ('식품/생활_고가', 3051), ('식품/생활_저가', 4149), ('식품/생활_중가', 3177), ('의류/이미용_고가', 1102), ('의류/이미용_저가', 1091), ('의류/이미용_중가', 2350), ('침구/주방_고가', 323), ('침구/주방_저가', 36), ('침구/주방_중가', 85)]

,1분기 중요 카테고리 top_1,1분기 중요 카테고리 top_2,2분기 중요 카테고리 top_1,2분기 중요 카테고리 top_2,3분기 중요 카테고리 top_1,3분기 중요 카테고리 top_2,4분기 중요 카테고리 top_1,4분기 중요 카테고리 top_2,5분기 중요 카테고리 top_1,5분기 중요 카테고리 top_2,6분기 중요 카테고리 top_1,6분기 중요 카테고리 top_2,7분기 중요 카테고리 top_1,7분기 중요 카테고리 top_2,8분기 중요 카테고리 top_1,8분기 중요 카테고리 top_2
가구인테리어/잡화_고가,947,618,955,609,911,601,1003,654,1038,647,1086,644,1079,649,1134,687
가구인테리어/잡화_저가,72,211,65,166,69,208,45,138,51,176,42,111,46,160,62,142
가구인테리어/잡화_중가,335,769,279,693,260,744,286,665,328,714,258,668,254,632,258,651
가전/레저취미/멀티샵_고가,419,326,381,381,372,323,385,404,395,349,358,408,377,329,397,409
가전/레저취미/멀티샵_저가,28,150,25,145,18,126,28,112,31,62,22,75,22,75,24,96
가전/레저취미/멀티샵_중가,541,994,427,947,471,956,529,907,464,843,313,777,432,879,480,884
교육문화/아동_고가,9,36,9,28,7,26,7,27,14,66,19,76,20,103,14,58
교육문화/아동_저가,21,50,19,58,18,63,14,51,11,28,8,44,11,39,17,32
교육문화/아동_중가,304,637,286,583,310,634,268,561,285,504,254,526,254,560,264,543
식품/생활_고가,628,2267,625,2536,703,2236,645,2962,667,2337,698,2562,724,2399,719,3051
식품/생활_저가,244,4194,267,4162,270,4284,208,4203,269,4700,308,4680,293,4645,210,4149
식품/생활_중가,10126,3163,10227,2951,10208,3117,10500,3097,10318,3239,10415,2960,10416,3034,10380,3177
의류/이미용_고가,976,1361,1005,1428,1017,1418,917,1189,945,1311,839,1433,944,1393,895,1102
의류/이미용_저가,345,1188,330,1296,313,1179,448,1221,471,1237,418,1252,358,1211,424,1091
의류/이미용_중가,3627,2453,3697,2459,3696,2513,3339,2243,3359,2246,3595,2288,3408,2342,3312,2350
침구/주방_고가,210,305,219,292,177,303,199,314,184,310,195,271,182,314,224,323
침구/주방_저가,4,50,5,40,4,35,3,45,2,13,1,14,NaN,17,6,36
침구/주방_중가,30,94,45,92,42,100,42,73,34,84,37,77,46,85,46,85

In [218]:
cate_df.transpose()

,가구인테리어/잡화_고가,가구인테리어/잡화_저가,가구인테리어/잡화_중가,가전/레저취미/멀티샵_고가,가전/레저취미/멀티샵_저가,가전/레저취미/멀티샵_중가,교육문화/아동_고가,교육문화/아동_저가,교육문화/아동_중가,식품/생활_고가,식품/생활_저가,식품/생활_중가,의류/이미용_고가,의류/이미용_저가,의류/이미용_중가,침구/주방_고가,침구/주방_저가,침구/주방_중가
1분기 중요 카테고리 top_1,947,72,335,419,28,541,9,21,304,628,244,10126,976,345,3627,210,4,30
1분기 중요 카테고리 top_2,618,211,769,326,150,994,36,50,637,2267,4194,3163,1361,1188,2453,305,50,94
2분기 중요 카테고리 top_1,955,65,279,381,25,427,9,19,286,625,267,10227,1005,330,3697,219,5,45
2분기 중요 카테고리 top_2,609,166,693,381,145,947,28,58,583,2536,4162,2951,1428,1296,2459,292,40,92
3분기 중요 카테고리 top_1,911,69,260,372,18,471,7,18,310,703,270,10208,1017,313,3696,177,4,42
3분기 중요 카테고리 top_2,601,208,744,323,126,956,26,63,634,2236,4284,3117,1418,1179,2513,303,35,100
4분기 중요 카테고리 top_1,1003,45,286,385,28,529,7,14,268,645,208,10500,917,448,3339,199,3,42
4분기 중요 카테고리 top_2,654,138,665,404,112,907,27,51,561,2962,4203,3097,1189,1221,2243,314,45,73
5분기 중요 카테고리 top_1,1038,51,328,395,31,464,14,11,285,667,269,10318,945,471,3359,184,2,34
5분기 중요 카테고리 top_2,647,176,714,349,62,843,66,28,504,2337,4700,3239,1311,1237,2246,310,13,84
6분기 중요 카테고리 top_1,1086,42,258,358,22,313,19,8,254,698,308,10415,839,418,3595,195,1,37
6분기 중요 카테고리 top_2,644,111,668,408,75,777,76,44,526,2562,4680,2960,1433,1252,2288,271,14,77
7분기 중요 카테고리 top_1,1079,46,254,377,22,432,20,11,254,724,293,10416,944,358,3408,182,NaN,46
7분기 중요 카테고리 top_2,649,160,632,329,75,879,103,39,560,2399,4645,3034,1393,1211,2342,314,17,85
8분기 중요 카테고리 top_1,1134,62,258,397,24,480,14,17,264,719,210,10380,895,424,3312,224,6,46
8분기 중요 카테고리 top_2,687,142,651,409,96,884,58,32,543,3051,4149,3177,1102,1091,2350,323,36,85

In [220]:
cate_df.to_csv('TOP2_카테고리빈도수확인.csv')
cate_df.to_excel('TOP2_카테고리빈도수확인.xlsx')

In [202]:
sorted(category.items())

[('가구인테리어/잡화_고가', 687),
 ('가구인테리어/잡화_저가', 142),
 ('가구인테리어/잡화_중가', 651),
 ('가전/레저취미/멀티샵_고가', 409),
 ('가전/레저취미/멀티샵_저가', 96),
 ('가전/레저취미/멀티샵_중가', 884),
 ('교육문화/아동_고가', 58),
 ('교육문화/아동_저가', 32),
 ('교육문화/아동_중가', 543),
 ('식품/생활_고가', 3051),
 ('식품/생활_저가', 4149),
 ('식품/생활_중가', 3177),
 ('의류/이미용_고가', 1102),
 ('의류/이미용_저가', 1091),
 ('의류/이미용_중가', 2350),
 ('침구/주방_고가', 323),
 ('침구/주방_저가', 36),
 ('침구/주방_중가', 85)]

In [206]:
category

{'침구/주방_중가': 85,
 '의류/이미용_중가': 2350,
 '식품/생활_중가': 3177,
 '의류/이미용_고가': 1102,
 '식품/생활_저가': 4149,
 '가구인테리어/잡화_중가': 651,
 '침구/주방_고가': 323,
 '식품/생활_고가': 3051,
 '가전/레저취미/멀티샵_고가': 409,
 '의류/이미용_저가': 1091,
 '가구인테리어/잡화_저가': 142,
 '가전/레저취미/멀티샵_중가': 884,
 '가구인테리어/잡화_고가': 687,
 '교육문화/아동_중가': 543,
 '교육문화/아동_저가': 32,
 '침구/주방_저가': 36,
 '교육문화/아동_고가': 58,
 '가전/레저취미/멀티샵_저가': 96}

In [214]:
for cat, val in category.items():
    cat
val
cat

'가전/레저취미/멀티샵_저가'

In [141]:
for i in total_df.columns:
    df = total_df[[i]]
    
df

                            8분기 중요 카테고리 top_2
CUSTNO
1             {'침구/주방_중가': 625313.0312615287}
2          [{'의류/이미용_중가': 2311184.722988136}]
3           [{'식품/생활_중가': 108123.3843828506}]
4          [{'의류/이미용_중가': 435737.6180935461}]
6           [{'식품/생활_중가': 747108.1097935721}]
...                                       ...
19333       [{'식품/생활_저가': 28544.00259200446}]
19334    [{'교육문화/아동_중가': 101631.02719622408}]
19335     [{'교육문화/아동_중가': 583594.0058328143}]
19336   [{'가구인테리어/잡화_저가': 615353.3616118222}]
19337       [{'식품/생활_저가': 366279.8294214492}]

[18866 rows x 1 columns]

In [167]:
list(df.loc[19336][0][0].keys())[0]

'가구인테리어/잡화_저가'

In [96]:
total_df.columns[0]

'1분기 중요 카테고리 top_1'

In [133]:
name = total_df.loc[1, total_df.columns[0]].keys()
list(name)[0]

'의류/이미용_중가'

In [135]:
category = {}
if list(name)[0] in category.keys():
    category[list(name)[0]] +=1
else:
    category[list(name)[0]] = 1
category

{'의류/이미용_중가': 1}

In [94]:
total_df.loc[14323]

1분기 중요 카테고리 top_1     [{'가구인테리어/잡화_고가': 284417008.6762252}]
1분기 중요 카테고리 top_2         [{'식품/생활_중가': 361833.9746381046}]
2분기 중요 카테고리 top_1    [{'가구인테리어/잡화_고가': 180999752.22489613}]
2분기 중요 카테고리 top_2        [{'식품/생활_중가': 510571.65005471697}]
3분기 중요 카테고리 top_1         [{'식품/생활_중가': 524527.8268846769}]
3분기 중요 카테고리 top_2         [{'식품/생활_고가': 154123.9247539997}]
4분기 중요 카테고리 top_1         [{'식품/생활_중가': 495162.1610962716}]
4분기 중요 카테고리 top_2         [{'식품/생활_저가': 214692.7441030032}]
5분기 중요 카테고리 top_1         [{'식품/생활_중가': 1659458.088550274}]
5분기 중요 카테고리 top_2           [{'식품/생활_저가': 435654.11196568}]
6분기 중요 카테고리 top_1         [{'식품/생활_중가': 1266952.285167626}]
6분기 중요 카테고리 top_2         [{'식품/생활_저가': 285153.7490789079}]
7분기 중요 카테고리 top_1         [{'식품/생활_중가': 457986.9914197021}]
7분기 중요 카테고리 top_2       [{'교육문화/아동_중가': 173873.6221261309}]
8분기 중요 카테고리 top_1         [{'식품/생활_중가': 788080.4908532309}]
8분기 중요 카테고리 top_2        [{'교육문화/아동_중가': 387724.073972172}]
Name: 14323, dtype: object

In [89]:
dic_1
pd.Series(dic_1)

의류/이미용_중가    3.197202e+06
dtype: float64

In [84]:
dic_1

{'식품/생활_중가': 507607.8050355344}

In [91]:
# 빈 데이터 프레임
total_df = pd.DataFrame(index = year2014_q1.index)

In [92]:
total_df.loc[1, '중요 카테고리'] = [dic_1]

ValueError: Incompatible indexer with Series

In [81]:
total_df.loc[1, '중요 카테고리_1'] = 'a'

In [82]:
total_df

       중요 카테고리_1 중요 카테고리
CUSTNO
1              a       d
2            NaN     NaN
3            NaN     NaN
4            NaN     NaN
6            NaN     NaN
...          ...     ...
19333        NaN     NaN
19334        NaN     NaN
19335        NaN     NaN
19336        NaN     NaN
19337        NaN     NaN

[18866 rows x 2 columns]

# 1. 1-2분기 Target : 2-3분기

In [11]:
df1 = pd.read_csv('C:/cakd7/git/2차 프로젝트/second_projects/생성데이터/q2_q1_df.csv', index_col = 0)
df1.head()

,가구인테리어/잡화_고가_증감여부,가구인테리어/잡화_저가_증감여부,가구인테리어/잡화_중가_증감여부,가전/레저취미/멀티샵_고가_증감여부,가전/레저취미/멀티샵_저가_증감여부,가전/레저취미/멀티샵_중가_증감여부,교육문화/아동_고가_증감여부,교육문화/아동_저가_증감여부,교육문화/아동_중가_증감여부,식품/생활_고가_증감여부,식품/생활_저가_증감여부,식품/생활_중가_증감여부,의류/이미용_고가_증감여부,의류/이미용_저가_증감여부,의류/이미용_중가_증감여부,침구/주방_고가_증감여부,침구/주방_저가_증감여부,침구/주방_중가_증감여부
CUSTNO,,,,,,,,,,,,,,,,,,
1,0,2,4,3,0,1,0,0,2,4,4,1,2,0,3,1,0,1
2,0,2,3,2,1,4,0,0,4,3,0,2,2,0,4,2,0,2
3,0,3,0,0,0,0,0,0,0,3,3,4,0,0,4,0,0,0
4,0,2,3,4,4,2,0,0,0,4,4,4,4,2,4,0,4,1
6,4,4,4,0,4,0,0,0,0,2,1,3,2,3,4,4,2,1

In [14]:
df1['total증감여부'] = total['1분기 대비2분기 증감여부']
df1.head()

,가구인테리어/잡화_고가_증감여부,가구인테리어/잡화_저가_증감여부,가구인테리어/잡화_중가_증감여부,가전/레저취미/멀티샵_고가_증감여부,가전/레저취미/멀티샵_저가_증감여부,가전/레저취미/멀티샵_중가_증감여부,교육문화/아동_고가_증감여부,교육문화/아동_저가_증감여부,교육문화/아동_중가_증감여부,식품/생활_고가_증감여부,식품/생활_저가_증감여부,식품/생활_중가_증감여부,의류/이미용_고가_증감여부,의류/이미용_저가_증감여부,의류/이미용_중가_증감여부,침구/주방_고가_증감여부,침구/주방_저가_증감여부,침구/주방_중가_증감여부,total증감여부
CUSTNO,,,,,,,,,,,,,,,,,,,
1,0,2,4,3,0,1,0,0,2,4,4,1,2,0,3,1,0,1,3
2,0,2,3,2,1,4,0,0,4,3,0,2,2,0,4,2,0,2,2
3,0,3,0,0,0,0,0,0,0,3,3,4,0,0,4,0,0,0,4
4,0,2,3,4,4,2,0,0,0,4,4,4,4,2,4,0,4,1,4
6,4,4,4,0,4,0,0,0,0,2,1,3,2,3,4,4,2,1,3

## 5분기 대비6분기

In [8]:
df6 = pd.read_csv('C:/cakd7/git/2차 프로젝트/second_projects/생성데이터/q6_q5_df.csv', index_col = 0)
df6.head()

,가구인테리어/잡화_고가_증감여부,가구인테리어/잡화_저가_증감여부,가구인테리어/잡화_중가_증감여부,가전/레저취미/멀티샵_고가_증감여부,가전/레저취미/멀티샵_저가_증감여부,가전/레저취미/멀티샵_중가_증감여부,교육문화/아동_고가_증감여부,교육문화/아동_저가_증감여부,교육문화/아동_중가_증감여부,식품/생활_고가_증감여부,식품/생활_저가_증감여부,식품/생활_중가_증감여부,의류/이미용_고가_증감여부,의류/이미용_저가_증감여부,의류/이미용_중가_증감여부,침구/주방_고가_증감여부,침구/주방_저가_증감여부,침구/주방_중가_증감여부
CUSTNO,,,,,,,,,,,,,,,,,,
1,2,2,1,1,0,1,0,0,0,3,3,1,3,0,3,2,1,1
2,1,3,1,2,1,0,0,0,1,1,4,1,2,4,3,1,0,4
3,0,4,0,0,0,0,0,0,0,1,3,3,0,0,0,0,0,0
4,0,4,4,0,0,3,0,4,0,4,4,2,4,4,2,1,0,0
6,4,3,4,0,0,0,0,0,0,2,1,1,3,3,4,1,1,1

## 6분기 대비 7분기

In [9]:
df7 = pd.read_csv('C:/cakd7/git/2차 프로젝트/second_projects/생성데이터/q7_q6_df.csv', index_col = 0)
df7.head()

,가구인테리어/잡화_고가_증감여부,가구인테리어/잡화_저가_증감여부,가구인테리어/잡화_중가_증감여부,가전/레저취미/멀티샵_고가_증감여부,가전/레저취미/멀티샵_저가_증감여부,가전/레저취미/멀티샵_중가_증감여부,교육문화/아동_고가_증감여부,교육문화/아동_저가_증감여부,교육문화/아동_중가_증감여부,식품/생활_고가_증감여부,식품/생활_저가_증감여부,식품/생활_중가_증감여부,의류/이미용_고가_증감여부,의류/이미용_저가_증감여부,의류/이미용_중가_증감여부,침구/주방_고가_증감여부,침구/주방_저가_증감여부,침구/주방_중가_증감여부
CUSTNO,,,,,,,,,,,,,,,,,,
1,1,1,4,4,0,3,0,0,0,1,1,1,1,0,3,3,0,0
2,0,3,0,4,0,0,0,0,4,4,1,2,2,1,4,3,0,1
3,0,3,0,0,4,0,0,0,0,4,1,4,0,0,0,0,0,0
4,0,2,4,0,4,4,0,1,0,1,1,2,1,4,3,4,0,0
6,3,1,4,0,0,0,0,4,0,4,4,4,2,3,3,0,4,4

In [10]:
df_total = df7 - df6
df_total

,가구인테리어/잡화_고가_증감여부,가구인테리어/잡화_저가_증감여부,가구인테리어/잡화_중가_증감여부,가전/레저취미/멀티샵_고가_증감여부,가전/레저취미/멀티샵_저가_증감여부,가전/레저취미/멀티샵_중가_증감여부,교육문화/아동_고가_증감여부,교육문화/아동_저가_증감여부,교육문화/아동_중가_증감여부,식품/생활_고가_증감여부,식품/생활_저가_증감여부,식품/생활_중가_증감여부,의류/이미용_고가_증감여부,의류/이미용_저가_증감여부,의류/이미용_중가_증감여부,침구/주방_고가_증감여부,침구/주방_저가_증감여부,침구/주방_중가_증감여부
CUSTNO,,,,,,,,,,,,,,,,,,
1,-1,-1,3,3,0,2,0,0,0,-2,-2,0,-2,0,0,1,-1,-1
2,-1,0,-1,2,-1,0,0,0,3,3,-3,1,0,-3,1,2,0,-3
3,0,-1,0,0,4,0,0,0,0,3,-2,1,0,0,0,0,0,0
4,0,-2,0,0,4,1,0,-3,0,-3,-3,0,-3,0,1,3,0,0
6,-1,-2,0,0,0,0,0,4,0,2,3,3,-1,0,-1,-1,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0,0,0,0,0,0,0,0,0,-3,1,0,0,0,0,0,0,0
19334,0,-1,0,0,0,0,3,-2,3,-2,-1,0,0,-2,4,0,0,0
19335,0,-2,-3,0,0,-3,-1,0,0,-3,2,0,-3,0,-1,0,-2,-1
19336,-1,4,0,0,0,-3,0,0,3,3,0,3,0,-1,1,-1,0,4
19337,0,0,0,0,4,0,0,-1,0,-3,0,1,0,0,-1,0,0,0