In [4]:
import warnings
warnings.filterwarnings('ignore')

from matplotlib import font_manager,rc

rc('font', family='Malgun Gothic')
plt.rcParams['axes.unicode_minus']=False     # 마이너스 부호 깨짐 방지

import pandas as pd
import numpy as np

In [22]:
# 분기별 매출액 데이터
weight_plus_q1 = pd.read_csv('weight_plus_2014_q1.csv', index_col = 0)
weight_plus_q2 = pd.read_csv('weight_plus_2014_q2.csv', index_col = 0)
weight_plus_q3 = pd.read_csv('weight_plus_2014_q3.csv', index_col = 0)
weight_plus_q4 = pd.read_csv('weight_plus_2014_q4.csv', index_col = 0)
weight_plus_q5 = pd.read_csv('weight_plus_2015_q1.csv', index_col = 0)
weight_plus_q6 = pd.read_csv('weight_plus_2015_q2.csv', index_col = 0)
weight_plus_q7 = pd.read_csv('weight_plus_2015_q3.csv', index_col = 0)
weight_plus_q8 = pd.read_csv('weight_plus_2015_q4.csv', index_col = 0)

In [137]:
# 감소증가 (0, 1, 2, 3, 4)
q2_q1_df = pd.read_csv('q2_q1_df.csv', index_col = 0)
q3_q2_df = pd.read_csv('q3_q2_df.csv', index_col = 0)
q4_q3_df = pd.read_csv('q4_q3_df.csv', index_col = 0)
q5_q4_df= pd.read_csv('q5_q4_df,.csv', index_col = 0)
q6_q5_df = pd.read_csv('q6_q5_df.csv', index_col = 0)
q7_q6_df = pd.read_csv('q7_q6_df.csv', index_col = 0)
q8_q7_df = pd.read_csv('q8_q7_df.csv', index_col = 0)

In [8]:
q7_q6_df

,가구인테리어/잡화_고가_증감여부,가구인테리어/잡화_저가_증감여부,가구인테리어/잡화_중가_증감여부,가전/레저취미/멀티샵_고가_증감여부,가전/레저취미/멀티샵_저가_증감여부,가전/레저취미/멀티샵_중가_증감여부,교육문화/아동_고가_증감여부,교육문화/아동_저가_증감여부,교육문화/아동_중가_증감여부,식품/생활_고가_증감여부,식품/생활_저가_증감여부,식품/생활_중가_증감여부,의류/이미용_고가_증감여부,의류/이미용_저가_증감여부,의류/이미용_중가_증감여부,침구/주방_고가_증감여부,침구/주방_저가_증감여부,침구/주방_중가_증감여부
CUSTNO,,,,,,,,,,,,,,,,,,
1,1,1,4,4,0,3,0,0,0,1,1,1,1,0,3,3,0,0
2,0,3,0,4,0,0,0,0,4,4,1,2,2,1,4,3,0,1
3,0,3,0,0,4,0,0,0,0,4,1,4,0,0,0,0,0,0
4,0,2,4,0,4,4,0,1,0,1,1,2,1,4,3,4,0,0
6,3,1,4,0,0,0,0,4,0,4,4,4,2,3,3,0,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19333,0,0,0,0,0,0,0,0,0,1,2,1,0,0,0,0,0,0
19334,0,1,0,0,0,0,4,1,4,1,1,1,0,1,4,0,1,0
19335,0,2,1,0,3,1,3,2,3,1,3,2,1,1,0,0,2,0
19336,3,4,3,0,0,1,0,0,4,4,0,4,2,0,4,0,0,4
19337,0,0,0,0,4,0,0,0,0,1,4,4,0,0,0,0,2,0

# 전체 증가변동폭

In [ ]:
columns = []
for i in range(1, 6):
    column = str(i) + '_' + str(i+1) + ' 대비 ' + str(i+1) + '_' + str(i+2) + ' 변동폭'
    columns.append(column)

total_cust = pd.DataFrame(q7_q6_df, columns = columns)
total_cust

In [33]:
all_cust = pd.DataFrame(index = q7_q6_df.index)
all_cust['1분기 총 매출'] = weight_plus_q1.sum(axis=1)
all_cust['2분기 총 매출'] = weight_plus_q2.sum(axis=1)
all_cust['3분기 총 매출'] = weight_plus_q3.sum(axis=1)
all_cust['4분기 총 매출'] = weight_plus_q4.sum(axis=1)
all_cust['5분기 총 매출'] = weight_plus_q5.sum(axis=1)
all_cust['6분기 총 매출'] = weight_plus_q6.sum(axis=1)
all_cust['7분기 총 매출'] = weight_plus_q7.sum(axis=1)
all_cust['8분기 총 매출'] = weight_plus_q8.sum(axis=1)

all_cust

,1분기 총 매출,2분기 총 매출,3분기 총 매출,4분기 총 매출,5분기 총 매출,6분기 총 매출,7분기 총 매출,8분기 총 매출
CUSTNO,,,,,,,,
1,9.357667e+06,1.136530e+07,1.259668e+07,1.968376e+07,9.662829e+06,8.941722e+06,9.256201e+06,4.385890e+06
2,1.475906e+07,1.040283e+07,1.693629e+07,6.173863e+06,1.947574e+07,9.635795e+06,1.607293e+07,1.013164e+07
3,3.071093e+05,5.559606e+05,6.222878e+05,4.091212e+05,2.855675e+05,3.127114e+05,3.968970e+05,2.623309e+05
4,1.348502e+06,3.825598e+06,2.793114e+06,1.581262e+06,1.758055e+06,1.991487e+06,2.388369e+06,1.484120e+06
6,2.176419e+06,3.193071e+06,3.428230e+06,2.662950e+06,3.789099e+06,2.898122e+06,3.786138e+06,2.896610e+06
...,...,...,...,...,...,...,...,...
19333,6.136198e+05,9.342699e+05,5.479324e+05,4.800637e+05,8.482479e+05,5.634833e+05,2.390725e+05,5.495308e+05
19334,8.370934e+05,2.729169e+06,2.462152e+06,2.888500e+06,1.764397e+06,7.803618e+05,5.706204e+05,3.945658e+05
19335,9.441858e+05,2.872725e+06,2.301145e+06,2.019960e+06,2.208095e+06,2.837039e+06,1.574717e+06,1.932177e+06
19336,4.712480e+05,3.528510e+06,3.722731e+06,4.874360e+06,2.984241e+06,3.712128e+06,7.618485e+06,4.015447e+06
19337,1.676168e+04,7.197679e+04,5.757769e+05,7.314457e+05,5.400619e+05,6.651010e+05,1.166340e+06,1.109442e+06

# !함수!: 전체 매출 증감폭 구하는 사용자 함수 생성

In [89]:
plus_minus_columns = []
for i in range(1, 8):
    column = str(i) + '분기 대비' + str(i+1) + '분기 증감여부'
    plus_minus_columns.append(column)
    
total_cust = pd.DataFrame(index = q7_q6_df.index, columns = plus_minus_columns)

for ind, name  in enumerate(total_cust.columns):
    before_name = all_cust.columns[ind]
    after_name = all_cust.columns[ind+1]
    # 평균 증감율 = (해당분기-전분기)/전분기
    before = all_cust[before_name] #전분기
    after = all_cust[after_name] #해당분기
    mean_ratio = (after.sum()-before.sum())/before.sum()

    # 기준금액 (전분기 매출*(1+증감율))
    mean_price = before*(1+mean_ratio)
    # 컬럼 추가
    stand_name = after_name + '비교 전분기_기준금액'
    all_cust[stand_name] = mean_price
    # 비교할 데이터만 추출
    new_cust = all_cust[[after_name, stand_name]]
 # 1. 증가할 고객 (해당분기금액 > 기준금액)
    new_plus_cust = new_cust[new_cust[after_name] > new_cust[stand_name]]
    
    # 증증가 고객 or 보통증가 고객 분류(4, 3)
    # 증가고객의 기존원본 데이터 총 매출
    plus_before = before.loc[new_plus_cust.index]
    plus_after = after.loc[new_plus_cust.index]
    
    # 증가고객의 평균 증가율
    mean_double_ratio = (plus_after.sum() - plus_before.sum())/ plus_before.sum()
        # 증가고객의 기준 금액이름
    new_plus_name = '증가고객기준_' + after_name
    # 증가고객의 기준 금액 데이터프레임에 추가
    new_plus_cust[new_plus_name] = plus_before * (1+mean_double_ratio)
    
#--나중에 대입할 증가고객 대상 -----
    # 증증가 고객
    double_plus = new_plus_cust[new_plus_cust[after_name] > new_plus_cust[new_plus_name]] # 증가기준금액보다 큰 경우
    # 보통증가 고객
    stand_plus = new_plus_cust[new_plus_cust[after_name] <= new_plus_cust[new_plus_name]] # 증가기준금액보다 작거나 같은 경우
    
#2. 감소고객 -- 
    new_minus_cust = new_cust[new_cust[after_name] < new_cust[stand_name]]
    
    # 짱감소 or 보통감소 고객 분류(1, 2)
    # 감소고객의 기존원본 데이터 총 매출
    minus_before = before.loc[new_minus_cust.index]
    minus_after = after.loc[new_minus_cust.index]
    
    # 감소고객의 평균 감소율
    minus_mean_ratio = (minus_after.sum() - minus_before.sum())/minus_before.sum()
        # 감소고객의 기준 금액이름
    new_minus_name = '감소고객기준_' + after_name
    # 감소고객의 기준 금액 추가
    new_minus_cust[new_minus_name] = minus_before * (1+minus_mean_ratio)

#--나중에 대입할 감소고객 대상--
    # 짱감소고객
    double_minus = new_minus_cust[new_minus_cust[after_name] < new_minus_cust[new_minus_name]]
    # 보통 감소고객
    stand_minus = new_minus_cust[new_minus_cust[after_name] >= new_minus_cust[new_minus_name]]

# --대입할 변화x 고객대상--
    new_same_cust = new_cust[new_cust[after_name] == new_cust[stand_name]]
    #--total_cust에 대입
    total_column_name = name
    # 증증가면 4
    total_cust.loc[double_plus.index, total_column_name] = 4
    # 보통증가면 3
    total_cust.loc[stand_plus.index, total_column_name] = 3
    # 보통감소면 2
    total_cust.loc[stand_minus.index, total_column_name] = 2
    # 짱감소면 1
    total_cust.loc[double_minus.index, total_column_name] = 1
    # 같으면 0
    total_cust.loc[new_same_cust.index, total_column_name] = 0
    
total_cust

,1분기 대비2분기 증감여부,2분기 대비3분기 증감여부,3분기 대비4분기 증감여부,4분기 대비5분기 증감여부,5분기 대비6분기 증감여부,6분기 대비7분기 증감여부,7분기 대비8분기 증감여부
CUSTNO,,,,,,,
1,3,3,3,1,2,3,1
2,2,4,1,4,1,4,2
3,4,3,2,2,3,3,2
4,4,2,1,3,3,3,2
6,3,3,2,3,2,3,2
...,...,...,...,...,...,...,...
19333,3,1,2,4,2,1,4
19334,4,2,3,1,1,2,2
19335,4,2,2,3,3,1,3
19336,4,3,3,1,3,4,1
19337,4,4,3,2,3,4,2

## 전체 매출 증감폭

In [102]:
for ind in range(1, len(total_cust.columns)):
    before_ind = total_cust.columns[ind-1]
    after_ind = total_cust.columns[ind]
    print(before_ind)
    print(ind-1)
    print(ind)
    print(after_ind)

1분기 대비2분기 증감여부
0
1
2분기 대비3분기 증감여부
2분기 대비3분기 증감여부
1
2
3분기 대비4분기 증감여부
3분기 대비4분기 증감여부
2
3
4분기 대비5분기 증감여부
4분기 대비5분기 증감여부
3
4
5분기 대비6분기 증감여부
5분기 대비6분기 증감여부
4
5
6분기 대비7분기 증감여부
6분기 대비7분기 증감여부
5
6
7분기 대비8분기 증감여부

In [108]:
total_cust_ratio = pd.DataFrame(index = total_cust.index)

for ind in range(1, len(total_cust.columns)):
    before_ind = total_cust.columns[ind -1]
    after_ind = total_cust.columns[ind]
    
    before_df = total_cust[before_ind]
    after_ind = total_cust[after_ind]
    
    new_columns = str(ind) + '_' + str(ind+1) + '증감폭 대비' + str(ind+1) + '_' + str(ind+2) + '변동폭' 
    total_cust_ratio[new_columns] = after_ind - before_df
    
total_cust_ratio

,1_2증감폭 대비2_3변동폭,2_3증감폭 대비3_4변동폭,3_4증감폭 대비4_5변동폭,4_5증감폭 대비5_6변동폭,5_6증감폭 대비6_7변동폭,6_7증감폭 대비7_8변동폭
CUSTNO,,,,,,
1,0,0,-2,1,1,-2
2,2,-3,3,-3,3,-2
3,-1,-1,0,1,0,-1
4,-2,-1,2,0,0,-1
6,0,-1,1,-1,1,-1
...,...,...,...,...,...,...
19333,-2,1,2,-2,-1,3
19334,-2,1,-2,0,1,0
19335,-2,0,1,0,-2,2
19336,-1,0,-2,2,1,-3
19337,0,-1,-1,1,1,-2

In [104]:
total_cust

,1분기 대비2분기 증감여부,2분기 대비3분기 증감여부,3분기 대비4분기 증감여부,4분기 대비5분기 증감여부,5분기 대비6분기 증감여부,6분기 대비7분기 증감여부,7분기 대비8분기 증감여부
CUSTNO,,,,,,,
1,3,3,3,1,2,3,1
2,2,4,1,4,1,4,2
3,4,3,2,2,3,3,2
4,4,2,1,3,3,3,2
6,3,3,2,3,2,3,2
...,...,...,...,...,...,...,...
19333,3,1,2,4,2,1,4
19334,4,2,3,1,1,2,2
19335,4,2,2,3,3,1,3
19336,4,3,3,1,3,4,1
19337,4,4,3,2,3,4,2

## 전체 데이터 파일저장

In [105]:
total_cust_ratio.to_csv('total_cust_ratio.csv')
total_cust.to_csv('total_cust.csv')

# 카테고리별 증감폭 구하기

In [110]:
columns = []
for i in range(1, 7):
    column = str(i) + '_' + str(i+1) + '증감폭 대비' + str(i+1) + '_' + str(i+2) + '변동폭'
    columns.append(column)
    
category_cust = pd.DataFrame(index = q7_q6_df.index, columns = columns)
category_cust

,1_2증감폭 대비2_3변동폭,2_3증감폭 대비3_4변동폭,3_4증감폭 대비4_5변동폭,4_5증감폭 대비5_6변동폭,5_6증감폭 대비6_7변동폭,6_7증감폭 대비7_8변동폭
CUSTNO,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
19333,NaN,NaN,NaN,NaN,NaN,NaN
19334,NaN,NaN,NaN,NaN,NaN,NaN
19335,NaN,NaN,NaN,NaN,NaN,NaN
19336,NaN,NaN,NaN,NaN,NaN,NaN
19337,NaN,NaN,NaN,NaN,NaN,NaN

## !함수! : 카테고리별 변동폭 구하는 함수 생성

In [164]:
columns_li = q2_q1_df.columns

# 18개의 컬럼리스트와, 해당 컬럼 인덱스 번호 입력시 해당 카테고리의 전체 변동폭 출력
def category_df(columns_, name_idx):
    # 컬럼이름
    i = columns_li[name_idx]
    category_cust[category_cust.columns[0]] = q3_q2_df[i] - q2_q1_df[i] # 1_2증감폭 대비2_3변동폭
    category_cust[category_cust.columns[1]] = q4_q3_df[i] - q3_q2_df[i] # 2_3증감폭 대비3_4변동폭
    category_cust[category_cust.columns[2]] = q5_q4_df[i] - q4_q3_df[i] # 3_4증감폭 대비4_5변동폭
    category_cust[category_cust.columns[3]] = q6_q5_df[i] - q5_q4_df[i] # 4_5증감폭 대비5_6변동폭
    category_cust[category_cust.columns[4]] = q7_q6_df[i] - q6_q5_df[i] # 5_6증감폭 대비6_7변동폭
    category_cust[category_cust.columns[5]] = q8_q7_df[i] - q7_q6_df[i] # 6_7증감폭 대비7_8변동폭

    category_cust_ = category_cust.copy()
    return category_cust_, i

In [165]:
# '가구인테리어/잡화_고가_증감여부'
first_df, name = category_df(columns_li, 17)
first_df

,1_2증감폭 대비2_3변동폭,2_3증감폭 대비3_4변동폭,3_4증감폭 대비4_5변동폭,4_5증감폭 대비5_6변동폭,5_6증감폭 대비6_7변동폭,6_7증감폭 대비7_8변동폭
CUSTNO,,,,,,
1,3,-2,0,-1,-1,4
2,2,-3,0,3,-3,2
3,0,0,0,0,0,0
4,3,-2,-1,-1,0,4
6,-1,4,-1,-2,3,-3
...,...,...,...,...,...,...
19333,0,0,0,0,0,0
19334,0,0,0,0,0,0
19335,-3,3,-2,-1,-1,0
19336,-2,-1,-1,0,4,-3
19337,0,0,0,0,0,0

## 카테고리별 출력해보기

In [162]:
for i, name in enumerate(q4_q3_df.columns):
    print(f'##################{i}카테고리 전체 변동폭 ##################')
    print(category_df(columns_li, i))

##################0카테고리 전체 변동폭 ##################
가구인테리어/잡화_고가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                     4               -3                3               -2
2                     0                4                0               -3
3                     0                0                0                0
4                     0                0                0                0
6                    -1               -2               -1                4
...                 ...              ...              ...              ...
19333                 0                0                0                0
19334                 0                0                0                0
19335                 0                0                0                0
19336                 0                4               -3                3
19337                 0                0                0                0

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                    -1               -1
2                    -1                0
3                     0                0
4                     0                0
6                    -1               -2
...                 ...              ...
19333                 0                0
19334                 0                0
19335                 0                0
19336                -1               -1
19337                 0                0

[18866 rows x 6 columns]
##################1카테고리 전체 변동폭 ##################
가구인테리어/잡화_저가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                    -1                3               -3                1
2                     1               -1                1                0
3                     1               -3                0                3
4                     1               -1                0                2
6                    -3                2                1               -1
...                 ...              ...              ...              ...
19333                -2                1               -2               -1
19334                 4                0               -2                0
19335                 1               -3                1                2
19336                -1                0               -2               -1
19337                 4               -2               -1               -1

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                    -1                3
2                     0               -2
3                    -1               -1
4                    -2                1
6                    -2                2
...                 ...              ...
19333                 0                0
19334                -1               -1
19335                -2               -1
19336                 4               -1
19337                 0                0

[18866 rows x 6 columns]
##################2카테고리 전체 변동폭 ##################
가구인테리어/잡화_중가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                    -3                2                1               -3
2                    -2               -1                4               -3
3                     0                0                0                0
4                    -2               -1                0                4
6                    -3                0               -1                4
...                 ...              ...              ...              ...
19333                 0                0                0                0
19334                 0                0                0                0
19335                 0                0                0                4
19336                -1               -2                3               -1
19337                 0                0                0                0

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                     3               -3
2                    -1                0
3                     0                0
4                     0               -3
6                     0               -3
...                 ...              ...
19333                 0                0
19334                 0                0
19335                -3               -1
19336                 0                0
19337                 0                4

[18866 rows x 6 columns]
##################3카테고리 전체 변동폭 ##################
가전/레저취미/멀티샵_고가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                    -2                3               -3                0
2                     1               -2                3               -2
3                     0                0                0                0
4                    -1               -2               -1                0
6                     0                0                0                0
...                 ...              ...              ...              ...
19333                 0                0                0                0
19334                 0                0                0                0
19335                 0                0                0                0
19336                 0                0                0                0
19337                 0                0                0                0

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                     3               -2
2                     2               -3
3                     0                0
4                     0                0
6                     0                4
...                 ...              ...
19333                 0                0
19334                 0                0
19335                 0                0
19336                 0                0
19337                 0                0

[18866 rows x 6 columns]
##################4카테고리 전체 변동폭 ##################
가전/레저취미/멀티샵_저가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                     0                0                0                0
2                    -1                4                0               -3
3                     4               -3               -1                0
4                    -3               -1                0                0
6                    -3               -1                0                0
...                 ...              ...              ...              ...
19333                -1                0                0                0
19334                -3                3               -3               -1
19335                -3                2                0                0
19336                 0                0                0                0
19337                 4               -3               -1                0

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                     0                0
2                    -1                0
3                     4               -3
4                     4               -3
6                     0                4
...                 ...              ...
19333                 0                0
19334                 0                4
19335                 0               -1
19336                 0                0
19337                 4               -2

[18866 rows x 6 columns]
##################5카테고리 전체 변동폭 ##################
가전/레저취미/멀티샵_중가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                     3                0                0               -3
2                    -3               -1                0                0
3                     0                0                0                0
4                     1               -1                0                1
6                     0                0                0                0
...                 ...              ...              ...              ...
19333                 0                0                0                0
19334                 0                0                0                0
19335                -3                0                3                0
19336                 3               -3                2                1
19337                 0                0                0                0

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                     2               -2
2                     0                0
3                     0                0
4                     1               -3
6                     0                0
...                 ...              ...
19333                 0                0
19334                 0                0
19335                -3               -1
19336                -3                2
19337                 0                0

[18866 rows x 6 columns]
##################6카테고리 전체 변동폭 ##################
교육문화/아동_고가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                     0                0                0                0
2                     0                0                0                0
3                     0                0                0                0
4                     0                0                0                0
6                     0                0                0                0
...                 ...              ...              ...              ...
19333                 0                0                0                0
19334                 4               -2                2               -3
19335                -2                0               -1                4
19336                 0                0                0                0
19337                 0                0                0                0

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                     0                0
2                     0                0
3                     0                0
4                     0                0
6                     0                0
...                 ...              ...
19333                 0                0
19334                 3                0
19335                -1               -2
19336                 0                0
19337                 0                0

[18866 rows x 6 columns]
##################7카테고리 전체 변동폭 ##################
교육문화/아동_저가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                     0                0                0                0
2                     0                0                0                0
3                     0                0                0                0
4                     0                0                0                4
6                     0                0                0                0
...                 ...              ...              ...              ...
19333                -1                0                0                0
19334                -2                2               -2                1
19335                -2                0                1               -1
19336                 0                0                0                0
19337                 0                0                4               -3

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                     0                0
2                     0                0
3                     0                0
4                    -3               -1
6                     4               -1
...                 ...              ...
19333                 0                0
19334                -2                0
19335                 0                0
19336                 0                0
19337                -1                0

[18866 rows x 6 columns]
##################8카테고리 전체 변동폭 ##################
교육문화/아동_중가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                    -1               -1                0                0
2                    -3                0                3               -3
3                     0                0                0                0
4                     0                0                0                0
6                     0                0                0                0
...                 ...              ...              ...              ...
19333                -2               -1                0                0
19334                -2                1                1               -3
19335                 0               -1                0                1
19336                 4               -3                3               -3
19337                 0                0                0                0

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                     0                0
2                     3               -3
3                     0                0
4                     0                0
6                     0                0
...                 ...              ...
19333                 0                0
19334                 3               -3
19335                 0                0
19336                 3               -3
19337                 0                0

[18866 rows x 6 columns]
##################9카테고리 전체 변동폭 ##################
식품/생활_고가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                    -3                3               -2                1
2                    -2                3               -1               -2
3                    -1                2               -3                0
4                    -3                1                2                0
6                     1               -1                1               -1
...                 ...              ...              ...              ...
19333                -3                3               -2                2
19334                -2                1               -2                2
19335                -2               -1                2                1
19336                -3                3               -2               -1
19337                 4                0               -3                3

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                    -2                3
2                     3               -2
3                     3               -3
4                    -3                3
6                     2               -2
...                 ...              ...
19333                -3                3
19334                -2                3
19335                -3                1
19336                 3               -3
19337                -3                3

[18866 rows x 6 columns]
##################10카테고리 전체 변동폭 ##################
식품/생활_저가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                     0                0               -3                2
2                     0                4               -3                3
3                    -1               -1                2                0
4                    -3                3               -3                3
6                     2               -1                1               -2
...                 ...              ...              ...              ...
19333                -1                3               -2               -1
19334                -1                1               -3                1
19335                -3                2                0               -2
19336                 0                0                0                0
19337                 0               -2               -1                3

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                    -2                3
2                    -3                0
3                    -2                2
4                    -3                1
6                     3               -2
...                 ...              ...
19333                 1                2
19334                -1                3
19335                 2               -1
19336                 0                0
19337                 0               -2

[18866 rows x 6 columns]
##################11카테고리 전체 변동폭 ##################
식품/생활_중가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                     3                0               -2               -1
2                     0                0                0               -1
3                     0               -3                0                2
4                    -3                1                2               -2
6                    -1                1                0               -2
...                 ...              ...              ...              ...
19333                -2                0                2               -3
19334                -2                0               -1                0
19335                -2                1               -1                0
19336                 0               -2               -1                0
19337                 0               -2                1                0

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                     0                1
2                     1                2
3                     1               -2
4                     0                1
6                     3               -1
...                 ...              ...
19333                 0                3
19334                 0                3
19335                 0                2
19336                 3               -2
19337                 1               -2

[18866 rows x 6 columns]
##################12카테고리 전체 변동폭 ##################
의류/이미용_고가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                     1               -2                2                0
2                     1               -1                2               -2
3                     0                0                0                0
4                    -2                0                0                2
6                     2               -2                0                1
...                 ...              ...              ...              ...
19333                 0                0                0                0
19334                 0                0                0                0
19335                 0                4               -3                3
19336                -1                1               -3                1
19337                 0                0                0                0

        5_6증감폭 대비6_7변동폭  6_7증감폭 대비7_8변동폭
CUSTNO
1                    -2                0
2                     0                1
3                     0                0
4                    -3                0
6                    -1                1
...                 ...              ...
19333                 0                0
19334                 0                0
19335                -3               -1
19336                 0                0
19337                 0                0

[18866 rows x 6 columns]
##################13카테고리 전체 변동폭 ##################
의류/이미용_저가_증감여부
        1_2증감폭 대비2_3변동폭  2_3증감폭 대비3_4변동폭  3_4증감폭 대비4_5변동폭  4_5증감폭 대비5_6변동폭  \
CUSTNO
1                     0                4               -3               -1
2                     0                0                0                4
3                     0                0                0                0
4                     2               -2               -1                3

## 파일 저장

In [167]:
columns_li

Index(['가구인테리어/잡화_고가_증감여부', '가구인테리어/잡화_저가_증감여부', '가구인테리어/잡화_중가_증감여부',
       '가전/레저취미/멀티샵_고가_증감여부', '가전/레저취미/멀티샵_저가_증감여부', '가전/레저취미/멀티샵_중가_증감여부',
       '교육문화/아동_고가_증감여부', '교육문화/아동_저가_증감여부', '교육문화/아동_중가_증감여부',
       '식품/생활_고가_증감여부', '식품/생활_저가_증감여부', '식품/생활_중가_증감여부', '의류/이미용_고가_증감여부',
       '의류/이미용_저가_증감여부', '의류/이미용_중가_증감여부', '침구/주방_고가_증감여부', '침구/주방_저가_증감여부',
       '침구/주방_중가_증감여부'],
      dtype='object')

In [172]:
df_li = []
for i in range(len(columns_li)):
    df_name = columns_li[i] + '_df'
    df_name, name = category_df(columns_li, i)
    df_li.append(df_name)
df_li[0]

,1_2증감폭 대비2_3변동폭,2_3증감폭 대비3_4변동폭,3_4증감폭 대비4_5변동폭,4_5증감폭 대비5_6변동폭,5_6증감폭 대비6_7변동폭,6_7증감폭 대비7_8변동폭
CUSTNO,,,,,,
1,4,-3,3,-2,-1,-1
2,0,4,0,-3,-1,0
3,0,0,0,0,0,0
4,0,0,0,0,0,0
6,-1,-2,-1,4,-1,-2
...,...,...,...,...,...,...
19333,0,0,0,0,0,0
19334,0,0,0,0,0,0
19335,0,0,0,0,0,0
19336,0,4,-3,3,-1,-1
19337,0,0,0,0,0,0

In [171]:
len(df_li)

18

In [180]:
columns_li[0][:-4].replace('/', '_')

'가구인테리어_잡화_고가_'

In [181]:
## 파일 저장
for i, name in enumerate(df_li):
    new_name = columns_li[i][:-4].replace('/', '_')
    file_name = new_name + '전체 증감폭_df'
    df_li[i].to_csv(f'{file_name}.csv')

In [182]:
pd.read_csv('가구인테리어_잡화_고가_전체 증감폭_df.csv')

,CUSTNO,1_2증감폭 대비2_3변동폭,2_3증감폭 대비3_4변동폭,3_4증감폭 대비4_5변동폭,4_5증감폭 대비5_6변동폭,5_6증감폭 대비6_7변동폭,6_7증감폭 대비7_8변동폭
0,1,4,-3,3,-2,-1,-1
1,2,0,4,0,-3,-1,0
2,3,0,0,0,0,0,0
3,4,0,0,0,0,0,0
4,6,-1,-2,-1,4,-1,-2
...,...,...,...,...,...,...,...
18861,19333,0,0,0,0,0,0
18862,19334,0,0,0,0,0,0
18863,19335,0,0,0,0,0,0
18864,19336,0,4,-3,3,-1,-1
18865,19337,0,0,0,0,0,0

In [169]:
가구인테리어_잡화_고가_df

,1_2증감폭 대비2_3변동폭,2_3증감폭 대비3_4변동폭,3_4증감폭 대비4_5변동폭,4_5증감폭 대비5_6변동폭,5_6증감폭 대비6_7변동폭,6_7증감폭 대비7_8변동폭
CUSTNO,,,,,,
1,4,-3,3,-2,-1,-1
2,0,4,0,-3,-1,0
3,0,0,0,0,0,0
4,0,0,0,0,0,0
6,-1,-2,-1,4,-1,-2
...,...,...,...,...,...,...
19333,0,0,0,0,0,0
19334,0,0,0,0,0,0
19335,0,0,0,0,0,0
19336,0,4,-3,3,-1,-1
19337,0,0,0,0,0,0